import {lazy,Suspense,useState} from 'react';
import type {Report} from '../types/analysis';
import {areaSummary,usablePoint,type Point} from '../lib/exploration';
const AreaMap=lazy(()=>import('./ServiceAreaMap'));
export function AreaExplorer({report}:{report:Report}){
 const [vertices,setVertices]=useState<Point[]>([]),[areas,setAreas]=useState<{name:string;points:Point[]}[]>([]),[name,setName]=useState('Proposed area'),[drawing,setDrawing]=useState(false),[lat,setLat]=useState(''),[lon,setLon]=useState(''),[error,setError]=useState('');
 const places=report.competitors.filter(p=>p.latitude!==null&&p.longitude!==null&&usablePoint([p.latitude,p.longitude]));
 function add(point:Point){if(!usablePoint(point)){setError('Enter valid coordinates (latitude between −85 and 85).');return}setVertices(v=>v.length<20?[...v,point]:v);setError('')}
 function save(){if(!areaSummary(vertices,places).area){setError('Draw 3–20 distinct vertices without crossing edges. Minimum area is 0.01 km²; all points must be within 100 km of the first.');return}if(!name.trim()){setError('Name this area.');return}setAreas([...areas,{name:name.trim(),points:vertices}]);setVertices([]);setDrawing(false);setError('')}
 return <section className="report-section" id="area-explorer"><h2>Underserved-area explorer</h2><p>Draw up to four service areas and compare the density of competitors returned by this search. All areas have incomplete search coverage; low counts cannot establish unmet demand.</p>{report.data_mode==='fixture'&&<p className="notice">Synthetic locations for demonstration.</p>}
 {places.length?<Suspense fallback={<p>Loading area map…</p>}><AreaMap places={places} vertices={vertices} areas={areas} add={add} drawing={drawing}/></Suspense>:<p className="empty">No usable coordinates. Create a fresh analysis with mapped competitors to use the map.</p>}
 <p>{places.length} mapped locations; {report.competitors.length-places.length} missing coordinates. Areas are temporary and reset when you leave the report.</p>
 <div className="report-actions"><button className="secondary" onClick={()=>setDrawing(!drawing)} disabled={!places.length||areas.length>=4}>{drawing?'Pause drawing':'Draw on map'}</button><button className="secondary" disabled={!vertices.length} onClick={()=>setVertices(vertices.slice(0,-1))}>Undo vertex</button><button className="secondary" onClick={()=>{setVertices([]);setAreas([]);setError('')}}>Clear areas</button></div>
 <p role="status">{drawing?'Click the map boundary points in order. Pause drawing to pan freely. ':''}{vertices.length}/20 vertices.</p>
 <details><summary>Enter boundary coordinates with the keyboard</summary><div className="research-form"><label>Vertex latitude<input type="number" step="any" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Vertex longitude<input type="number" step="any" value={lon} onChange={e=>setLon(e.target.value)}/></label></div><button className="secondary" disabled={vertices.length>=20||areas.length>=4} onClick={()=>{if(!lat.trim()||!lon.trim()){setError('Enter both coordinates.');return}add([Number(lat),Number(lon)])}}>Add vertex</button><ol>{vertices.map((p,i)=><li key={i}>{p.map(v=>v.toFixed(5)).join(', ')}</li>)}</ol></details>
 <div className="research-form"><label>Area name<input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={areas.length>=4||vertices.length<3} onClick={save}>Compare this area</button></div>{error&&<p role="alert">{error}</p>}
 {areas.length>0&&<div className="table-scroll"><table><thead><tr><th>Area</th><th>Approx. km²</th><th>Sampled locations / km²</th><th>Coverage</th></tr></thead><tbody>{areas.map((a,i)=>{const s=areaSummary(a.points,report.competitors);return <tr key={i}><th>{a.name}<details><summary>{s.members.length} locations</summary><ul>{s.members.map(p=><li key={p.rank}>{p.name}</li>)}</ul></details></th><td>{s.area?.toFixed(2)}</td><td>{s.density?.toFixed(2)}</td><td>{s.members.length<3?'Sparse evidence (fewer than 3 locations)':'Incomplete search sample'}{s.missing>0&&`; ${s.missing} locations cannot be assigned`}</td></tr>})}</tbody></table></div>}
 <p className="hint">Approximate local planar area. Boundary locations count as inside; overlapping areas can count the same location. Counts cover one search page, not a complete business census. Population, footfall, rent and travel time are unavailable.</p></section>;
}
