import {useEffect,useState} from 'react';

const conditions=['dataset','train/test split','preprocessing','compute budget','tuning budget','evaluation metric','evaluation protocol','method version and code'];
const fieldByCondition:Record<string,keyof Method>={dataset:'dataset','train/test split':'split',preprocessing:'preprocessing','compute budget':'compute','tuning budget':'tuning','evaluation metric':'metric','evaluation protocol':'protocol','method version and code':'version'};
type Method={name:string;dataset:string;split:string;preprocessing:string;compute:string;tuning:string;metric:string;protocol:string;version:string;source:string};
type Verdict='unreviewed'|'comparable'|'mismatch'|'justified difference';
type Assessment={verdict:Verdict;reason:string;evidence:string};
type Audit={proposed:Method;baseline:Method;assessments:Record<string,Assessment>};
const blankMethod=():Method=>({name:'',dataset:'',split:'',preprocessing:'',compute:'',tuning:'',metric:'',protocol:'',version:'',source:''});
const blankAudit=():Audit=>({proposed:blankMethod(),baseline:blankMethod(),assessments:{}});
function read(key:string):Audit{try{const value=JSON.parse(localStorage.getItem(key)||'null');if(!value)return blankAudit();return {proposed:{...blankMethod(),...value.proposed},baseline:{...blankMethod(),...value.baseline},assessments:value.assessments||{}}}catch{return blankAudit()}}

export function BaselineFairnessAudit({reportId}:{reportId:string}){
 const key='novelty-defense-'+reportId+'-baseline-fairness';
 const [audit,setAudit]=useState(()=>read(key));
 const [storageError,setStorageError]=useState(false);
 const persist=(next:Audit)=>{setAudit(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 useEffect(()=>{const listener=(event:Event)=>{const detail=(event as CustomEvent<{name:string;source:string}>).detail;if(!detail?.name)return;persist({...audit,baseline:{...audit.baseline,name:detail.name,source:detail.source||''}})};window.addEventListener('research-baseline-select',listener);return()=>window.removeEventListener('research-baseline-select',listener)},[audit]);
 const methodField=(side:'proposed'|'baseline',field:keyof Method,value:string)=>persist({...audit,[side]:{...audit[side],[field]:value}});
 const values:Record<string,[string,string]>={dataset:[audit.proposed.dataset,audit.baseline.dataset], 'train/test split':[audit.proposed.split,audit.baseline.split],preprocessing:[audit.proposed.preprocessing,audit.baseline.preprocessing],'compute budget':[audit.proposed.compute,audit.baseline.compute],'tuning budget':[audit.proposed.tuning,audit.baseline.tuning],'evaluation metric':[audit.proposed.metric,audit.baseline.metric],'evaluation protocol':[audit.proposed.protocol,audit.baseline.protocol],'method version and code':[audit.proposed.version,audit.baseline.version]};
 const assessments=conditions.map(condition=>{const [proposed,baseline]=values[condition];const assessment=audit.assessments[condition]||{verdict:'unreviewed' as Verdict,reason:'',evidence:''};const differs=Boolean(proposed&&baseline&&proposed.trim().toLocaleLowerCase()!==baseline.trim().toLocaleLowerCase());return {condition,proposed,baseline,assessment,differs}});
 const missing=assessments.filter(row=>!row.proposed.trim()||!row.baseline.trim()||row.assessment.verdict==='unreviewed'||!row.assessment.evidence.trim()||(row.assessment.verdict==='justified difference'&&!row.assessment.reason.trim()));
 const mismatches=assessments.filter(row=>row.assessment.verdict==='mismatch'||(row.differs&&row.assessment.verdict==='comparable'));
 const outcome=!audit.proposed.name||!audit.baseline.name?'Add both methods to start the audit.':missing.length?'Incomplete · '+missing.length+' conditions lack details or review.':mismatches.length?'Review required · '+mismatches.length+' conditions are mismatched or need explanation.':'All conditions have a recorded comparison; check justifications and supporting sources.';
 return <>
  <p>Compare one proposed method with one baseline. Record actual conditions and evidence; matching fields alone do not prove a fair experiment.</p>
  <div className="fairness-method-grid"><section><h4>Proposed method</h4><label>Method name<input value={audit.proposed.name} onChange={event=>methodField('proposed','name',event.target.value)}/></label><label>Reference or code URL<input type="url" value={audit.proposed.source} onChange={event=>methodField('proposed','source',event.target.value)}/></label></section><section><h4>Baseline</h4><label>Method name<input value={audit.baseline.name} onChange={event=>methodField('baseline','name',event.target.value)}/></label><label>Reference or code URL<input type="url" value={audit.baseline.source} onChange={event=>methodField('baseline','source',event.target.value)}/></label></section></div>
  <div className="fairness-condition-list">{assessments.map(({condition,proposed,baseline,assessment,differs})=><article key={condition}><header><b>{condition}</b>{differs&&<span className="warning-line">Entered values differ</span>}</header><div className="fairness-value-grid"><label>Proposed<input value={proposed} onChange={event=>methodField('proposed',fieldByCondition[condition],event.target.value)}/></label><label>Baseline<input value={baseline} onChange={event=>methodField('baseline',fieldByCondition[condition],event.target.value)}/></label></div><label>Assessment<select value={assessment.verdict} onChange={event=>persist({...audit,assessments:{...audit.assessments,[condition]:{...assessment,verdict:event.target.value as Verdict}}})}><option value="unreviewed">Not reviewed</option><option value="comparable">Comparable</option><option value="mismatch">Mismatch</option><option value="justified difference">Difference with justification</option></select></label><label>Reason or justification<textarea rows={2} value={assessment.reason} onChange={event=>persist({...audit,assessments:{...audit.assessments,[condition]:{...assessment,reason:event.target.value}}})} placeholder="Explain differences, controls, or unknown details"/></label><label>Evidence URL or artifact<input value={assessment.evidence} onChange={event=>persist({...audit,assessments:{...audit.assessments,[condition]:{...assessment,evidence:event.target.value}}})} placeholder="Citation, protocol, run log, or code version"/></label></article>)}</div>
  <div className="tool-result"><b>{outcome}</b><p>A difference marked as justified needs a written reason. Unknown conditions remain incomplete.</p></div>
  {storageError&&<p className="warning-line" role="alert">This baseline audit could not be saved in this browser.</p>}
  <small>This checklist supports review and does not establish that the methods are scientifically comparable.</small>
 </>;
}
