import {parseStoredRecord,writeStoredRecord} from '../lib/projectRecords';
import {useState} from 'react';
type Experiment={id:string;name:string;dataset:string;population:string;comparator:string;outcome:string;metric:string;threshold:string;analysis:string;repetitions:string;evidence:string;reviewed:boolean};
type Plans=Record<string,Experiment[]>;
const blank=():Experiment=>({id:crypto.randomUUID(),name:'',dataset:'',population:'',comparator:'',outcome:'',metric:'',threshold:'',analysis:'',repetitions:'',evidence:'',reviewed:false});
function read(key:string):Plans{try{const value=parseStoredRecord(key,'{}') as Record<string,unknown>;return Object.fromEntries(Object.entries(value).map(([claim,raw])=>{const items=Array.isArray(raw)?raw.map((item:any)=>({...blank(),...item,id:item.id||crypto.randomUUID()})):[{...blank(),...(raw as Partial<Experiment>)}];return [claim,items]}))}catch{return {}}}
const required:(keyof Experiment)[]=['name','dataset','comparator','outcome','metric','threshold','analysis'];
export function ClaimMeasurementAlignment({reportId,claims}:{reportId:string;claims:{id:string;text:string}[]}){
 const key='novelty-defense-'+reportId+'-measurements';const [plans,setPlans]=useState(()=>read(key));const [storageError,setStorageError]=useState(false);
 const persist=(next:Plans)=>{setPlans(next);try{writeStoredRecord(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const edit=(claimId:string,experiment:Experiment,patch:Partial<Experiment>)=>persist({...plans,[claimId]:(plans[claimId]||[]).map(item=>item.id===experiment.id?{...item,...patch,reviewed:patch.reviewed??(Object.keys(patch).some(field=>field!=='reviewed')?false:item.reviewed)}:item)});
 const add=(claimId:string)=>persist({...plans,[claimId]:[...(plans[claimId]||[]),blank()]});
 const remove=(claimId:string,id:string)=>persist({...plans,[claimId]:(plans[claimId]||[]).filter(item=>item.id!==id)});
 if(!claims.length)return <p className="empty-state">No claims are attached to this report. Add claims to the proposal, then map each claim to an experiment.</p>;
 return <>
  <p>For every research claim, define the experiment that tests it, the comparison condition, the outcome, and the acceptance rule. Mark a plan reviewed only after checking that the measurement represents the claim.</p>
  <div className="claim-experiment-map">{claims.map(claim=>{const experiments=plans[claim.id]||[];const ready=experiments.filter(experiment=>required.every(field=>String(experiment[field]).trim())&&experiment.reviewed).length;return <article key={claim.id}><header><b>{claim.text}</b><span>{ready}/{experiments.length} reviewed plans</span></header>{experiments.map((experiment,index)=>{const missing=required.filter(field=>!String(experiment[field]).trim());return <section className="claim-experiment" key={experiment.id}><header><h4>Experiment {index+1}</h4><button type="button" className="quiet-button" onClick={()=>remove(claim.id,experiment.id)}>Remove experiment</button></header><div className="tool-input-grid">{([['name','Experiment name'],['dataset','Dataset and version'],['population','Population or setting'],['comparator','Comparator or control'],['outcome','Primary outcome'],['metric','Metric and units'],['threshold','Success threshold'],['repetitions','Sample size or repetitions'],['evidence','Protocol or evidence link']] as const).map(([field,label])=><label key={field}>{label}<input value={experiment[field]} onChange={event=>edit(claim.id,experiment,{[field]:event.target.value})}/></label>)}</div><label>Analysis plan<textarea rows={2} value={experiment.analysis} onChange={event=>edit(claim.id,experiment,{analysis:event.target.value})} placeholder="Specify the planned comparison and how the result will be interpreted"/></label>{missing.length>0&&<p className="warning-line">Missing: {missing.join(', ')}.</p>}<label className="alignment-review"><input type="checkbox" checked={experiment.reviewed} disabled={missing.length>0} onChange={event=>edit(claim.id,experiment,{reviewed:event.target.checked})}/>I reviewed that this experiment measures the claim above.</label></section>})}<button type="button" className="quiet-button" onClick={()=>add(claim.id)}>Add experiment for this claim</button></article>})}</div>
  {storageError&&<p className="warning-line" role="alert">The experiment alignment plan could not be saved in this browser.</p>}
 </>;
}
