import {useState} from 'react';
import type {ResearchReport} from './MarketResearch';
import {days,openingState} from '../lib/marketTools';
const benefits={Pricing:'Affordable pricing',Service:'Responsive service',Cleanliness:'Well-maintained space',Facilities:'Reliable facilities',Flexibility:'Flexible terms'};
export function ConceptSandbox({report}:{report:ResearchReport}){
 const [concept,setConcept]=useState(''),[selected,setSelected]=useState<string[]>([]),[evening,setEvening]=useState(false),[day,setDay]=useState(0),[hour,setHour]=useState(19);
 const states=report.competitors.map(p=>openingState(p.operating_hours,day,hour*60));
 return <section className="report-section" id="concept-sandbox"><h2>Business concept sandbox</h2><p>Describe your offering and select the benefits you want to test against this report. Matching uses your selected topics, not an automated assessment of the description.</p><label>Proposed offering<textarea rows={2} maxLength={1000} value={concept} onChange={e=>setConcept(e.target.value)} placeholder="Quiet coworking with flexible evening access"/></label><fieldset className="concept-benefits"><legend>Benefits to investigate</legend>{Object.entries(benefits).map(([topic,label])=><label className="checkbox" key={topic}><input type="checkbox" checked={selected.includes(topic)} onChange={e=>setSelected(e.target.checked?[...selected,topic]:selected.filter(v=>v!==topic))}/>{label}</label>)}<label className="checkbox"><input type="checkbox" checked={evening} onChange={e=>setEvening(e.target.checked)}/>Access at a specific time</label></fieldset>
 {report.data_mode==='fixture'&&<p className="notice">Matches below use synthetic evidence.</p>}
 {selected.map(topic=>{const cells=(report.review_matrix||[]).flatMap(row=>row.topics[topic]?[{name:row.competitor,...row.topics[topic]}]:[]);const negative=cells.flatMap(c=>c.negative),positive=cells.flatMap(c=>c.positive);return <article className="concept-evidence" key={topic}><h3>{benefits[topic as keyof typeof benefits]}</h3><p>{negative.length} mentions in low-rated reviews · {positive.length} in highly rated reviews · {cells.length} sampled businesses.</p>{!cells.length?<p>No matching evidence is stored for this topic. This is an unanswered question.</p>:<details><summary>Inspect supporting and competing evidence</summary>{cells.map(c=><div key={c.name}><h4>{c.name}</h4>{[...c.negative,...c.positive].map((r,i)=><blockquote key={i}>{r.text}<footer>{r.rating}/5 · {r.published_at?.slice(0,10)||'Date unknown'} {r.source_url&&/^https?:\/\//i.test(r.source_url)&&<a href={r.source_url} target="_blank" rel="noopener noreferrer">Review source</a>}</footer></blockquote>)}</div>)}</details>}<p className="hint">Interview prompt: Tell me about the last time {topic.toLowerCase()} affected your choice. What did you do, and what did it cost you?</p></article>})}
 {evening&&<><div className="research-form"><label>Proposed access day<select value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Proposed access hour<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:24},(_,i)=><option key={i} value={i}>{String(i).padStart(2,'0')}:00</option>)}</select></label></div><p>{states.filter(s=>s==='Closed').length} competitors published closed · {states.filter(s=>s==='Open').length} open · {states.filter(s=>s==='Unknown').length} unknown. Ask customers when they last needed access at this time and what alternative they used.</p><a href="#hours-gaps">Inspect schedules and sources</a></>}
 {!selected.length&&!evening&&<p className="empty">Select a benefit to inspect the available evidence.</p>}
 <p>Unanswered for every concept: willingness to pay, frequency of the problem, customer segment size, and the cost of delivering your promise. Use the <a href="#validation-lab">customer validation lab</a> to investigate.</p><p className="hint">Whole-review ratings do not establish sentiment about each topic. Mentions can overlap, contradict your idea, or miss context. This temporary workspace does not change report scores.</p></section>;
}
