import {useState} from 'react';
type Comparison='same'|'different'|'unknown';
type Conditions={groups:string;assignment:'randomized'|'not randomized'|'unknown';dataset:Comparison;preprocessing:Comparison;compute:Comparison;tuning:Comparison;measurement:Comparison;siteTime:Comparison;missingness:Comparison;outcomeRegistered:'yes'|'no'|'unknown';attrition:Comparison};
type Risk={id:string;title:string;why:string;control:string;status:'unreviewed'|'controlled'|'unresolved'|'ruled out';evidence:string};
type Saved={conditions:Conditions;risks:Record<string,Risk>};
const blankConditions=():Conditions=>({groups:'',assignment:'unknown',dataset:'unknown',preprocessing:'unknown',compute:'unknown',tuning:'unknown',measurement:'unknown',siteTime:'unknown',missingness:'unknown',outcomeRegistered:'unknown',attrition:'unknown'});
const prompts=[{id:'selection',title:'Group assignment or selection',why:'Non-random assignment can leave groups different before the intervention.',condition:'assignment'},{id:'dataset',title:'Dataset or population differences',why:'Different populations, collection periods, or dataset versions can explain an apparent effect.',condition:'dataset'},{id:'preprocessing',title:'Preprocessing differences',why:'Different filtering, augmentation, or normalization can change outcomes.',condition:'preprocessing'},{id:'compute',title:'Compute or training budget differences',why:'More compute or training time can produce an apparent method gain.',condition:'compute'},{id:'tuning',title:'Hyperparameter tuning differences',why:'Different search budgets or access to the test set can favor one method.',condition:'tuning'},{id:'measurement',title:'Measurement or annotation differences',why:'Changed instruments, annotators, or metric implementations can shift results.',condition:'measurement'},{id:'site-time',title:'Site or time effects',why:'Collection site, season, or period can be associated with both the intervention and outcome.',condition:'siteTime'},{id:'missingness',title:'Missing data or attrition',why:'Unequal missingness or participant loss can bias the observed comparison.',condition:'missingness'},{id:'outcome',title:'Outcome selection after observing results',why:'Selecting outcomes after seeing the results increases the chance of a misleading finding.',condition:'outcomeRegistered'},{id:'attrition',title:'Unequal follow-up or dropouts',why:'Different follow-up or dropout rates can make groups incomparable.',condition:'attrition'}] as const;
function read(key:string):Saved{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value?{conditions:{...blankConditions(),...value.conditions},risks:value.risks||{}}:{conditions:blankConditions(),risks:{}}}catch{return {conditions:blankConditions(),risks:{}}}}
export function ConfounderFinder({reportId}:{reportId:string}){
 const key='novelty-defense-'+reportId+'-confounder-review';const [saved,setSaved]=useState(()=>read(key));const [storageError,setStorageError]=useState(false);
 const persist=(next:Saved)=>{setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const active=prompts.filter(prompt=>{const value=saved.conditions[prompt.condition];return prompt.id==='selection'?value!=='randomized':prompt.id==='outcome'?value!=='yes':value!=='same'});
 const editCondition=(field:keyof Conditions,value:string)=>persist({...saved,conditions:{...saved.conditions,[field]:value}});
 const updateRisk=(prompt:(typeof prompts)[number],patch:Partial<Risk>)=>{const current=saved.risks[prompt.id]||{id:prompt.id,title:prompt.title,why:prompt.why,control:'',status:'unreviewed' as const,evidence:''};persist({...saved,risks:{...saved.risks,[prompt.id]:{...current,...patch}}})};
 const unresolved=active.filter(prompt=>{const risk=saved.risks[prompt.id];return !risk||risk.status==='unresolved'||risk.status==='unreviewed'||((risk.status==='controlled'||risk.status==='ruled out')&&!risk.control.trim())}).length;
 return <>
  <p>Describe the study comparison. Prompts appear where a condition is different or unknown; review whether each factor could explain an apparent result and record a control or reason.</p>
  <label>Compared groups or conditions<input value={saved.conditions.groups} onChange={event=>editCondition('groups',event.target.value)} placeholder="e.g. intervention vs usual care"/></label>
  <div className="tool-input-grid">{([['assignment','Assignment randomized?',['randomized','not randomized','unknown']],['dataset','Dataset/population comparable?',['same','different','unknown']],['preprocessing','Preprocessing comparable?',['same','different','unknown']],['compute','Compute budget comparable?',['same','different','unknown']],['tuning','Tuning budget comparable?',['same','different','unknown']],['measurement','Outcome measurement comparable?',['same','different','unknown']],['siteTime','Site and time comparable?',['same','different','unknown']],['missingness','Missingness comparable?',['same','different','unknown']],['outcomeRegistered','Primary outcome pre-specified?',['yes','no','unknown']],['attrition','Follow-up and attrition comparable?',['same','different','unknown']]] as const).map(([field,label,options])=><label key={field}>{label}<select value={saved.conditions[field]} onChange={event=>editCondition(field,event.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>)}</div>
  <div className="coverage-strip"><span>Triggered prompts<b>{active.length}</b></span><span>Unresolved or unreviewed<b>{unresolved}</b></span></div>
  {active.length?active.map(prompt=>{const risk=saved.risks[prompt.id]||{id:prompt.id,title:prompt.title,why:prompt.why,control:'',status:'unreviewed' as const,evidence:''};return <article className="confounder-risk" key={prompt.id}><header><b>{prompt.title}</b><span>{saved.conditions[prompt.condition]}</span></header><p>{prompt.why}</p><label>Review status<select value={risk.status} onChange={event=>updateRisk(prompt,{status:event.target.value as Risk['status']})}><option value="unreviewed">Unreviewed</option><option value="controlled">Control planned or documented</option><option value="unresolved">Unresolved risk</option><option value="ruled out">Reviewed and ruled out</option></select></label><label>Control, evidence, or reason<textarea rows={2} value={risk.control} onChange={event=>updateRisk(prompt,{control:event.target.value})} placeholder="Describe a control, measurement, design change, or why it does not apply"/></label><label>Evidence or protocol link<input value={risk.evidence} onChange={event=>updateRisk(prompt,{evidence:event.target.value})}/></label>{risk.status==='controlled'&&!risk.control.trim()&&<p className="warning-line">Describe the control before treating this prompt as addressed.</p>}</article>}):<p className="empty-state">No differences or unknown conditions were entered. Confirm each study setting before treating this as a clean review.</p>}
  {storageError&&<p className="warning-line" role="alert">Confounder review could not be saved in this browser.</p>}
  <small>These prompts follow entered fields and do not establish causality. Have a domain expert review study-specific confounders.</small>
 </>;
}
