import {useState} from 'react';
import {z} from 'zod';
import type {Report} from '../types/analysis';
import {useLocalRecords} from '../lib/useLocalRecords';
const verdicts=['Unreviewed','Supported','Mixed','Contradicted'] as const;
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v});
export const decisionSchema=z.object({id:z.string(),created:z.string(),decision:z.string().trim().min(5).max(1000),assumptions:z.string().trim().min(5).max(3000),metric:z.string().trim().min(2).max(100),expected:z.number().finite(),reviewDate:date,baseline:z.number(),interpretation:z.string(),actual:z.number().finite().nullable(),reflection:z.string().max(5000),verdict:z.enum(verdicts),reviewedAt:z.string().nullable()});
type Decision=z.infer<typeof decisionSchema>;
function DecisionRecord({item,save}:{item:Decision;save:(v:Decision)=>boolean}){
 const [actual,setActual]=useState(item.actual===null?'':String(item.actual)),[reflection,setReflection]=useState(item.reflection),[verdict,setVerdict]=useState<Decision['verdict']>(item.verdict),[message,setMessage]=useState('');
 function update(){const parsed=decisionSchema.safeParse({...item,actual:actual.trim()===''?null:Number(actual),reflection,verdict,reviewedAt:new Date().toISOString()});if(!parsed.success){setMessage('Enter a finite numeric result.');return}if(verdict==='Unreviewed'||!reflection.trim()){setMessage('Choose a reviewed verdict and explain which assumptions held up.');return}setMessage(save(parsed.data)?'Review saved':'Could not save review; keep this tab open.')}
 const due=item.verdict==='Unreviewed'&&item.reviewDate<=new Date().toLocaleDateString('en-CA');
 return <details className="research-record"><summary>{item.decision} · {item.verdict}{due?' · Review due':''}</summary><p>Recorded {item.created.slice(0,10)} · review date {item.reviewDate}</p><p>Original report: {item.baseline}/100 · {item.interpretation}</p><h3>Original assumptions</h3><p className="preserve-lines">{item.assumptions}</p><p>Expected {item.metric}: {item.expected}</p>{item.actual!==null&&<p>Saved actual: {item.actual} · difference: {item.actual-item.expected>0?'+':''}{Number((item.actual-item.expected).toFixed(4))}. Whether higher is better depends on your metric.</p>}{item.reviewedAt&&<p>Last reviewed {item.reviewedAt.slice(0,10)}</p>}<div className="research-form"><label>Actual result (optional)<input type="number" step="any" value={actual} onChange={e=>setActual(e.target.value)}/></label><label>Assumption verdict<select value={verdict} onChange={e=>setVerdict(e.target.value as Decision['verdict'])}>{verdicts.map(v=><option key={v}>{v}</option>)}</select></label></div><label>Which assumptions held up?<textarea maxLength={5000} rows={3} value={reflection} onChange={e=>setReflection(e.target.value)}/></label><button className="secondary" onClick={update}>Save decision review</button><p role="status">{message}</p></details>;
}
export function DecisionJournal({report}:{report:Report}){
 const records=useLocalRecords('market-decisions-v1:'+report.id,decisionSchema);
 const [decision,setDecision]=useState(''),[assumptions,setAssumptions]=useState(''),[metric,setMetric]=useState(''),[expected,setExpected]=useState(''),[reviewDate,setReviewDate]=useState(''),[error,setError]=useState('');
 function create(){if(!expected.trim()){setError('Enter an expected numeric outcome.');return}const parsed=decisionSchema.safeParse({id:crypto.randomUUID(),created:new Date().toISOString(),decision,assumptions,metric,expected:Number(expected),reviewDate,baseline:report.overall_score,interpretation:report.interpretation,actual:null,reflection:'',verdict:'Unreviewed',reviewedAt:null});if(!parsed.success){setError('Complete the decision, assumptions, metric, numeric expectation and valid review date.');return}if(records.save([...records.items,parsed.data])){setDecision('');setError('')}}
 return <section className="report-section" id="decision-journal"><h2>Market-entry decision journal</h2><p>Record a decision and its expected outcome, then return to assess the assumptions. The original entry stays fixed; later reviews are saved separately within it.</p><p className="hint">Browser-local records for this report; excluded from shared links. Export a backup. Review dates appear here when you return; no reminders are sent.</p><label>Decision<textarea rows={2} maxLength={1000} value={decision} onChange={e=>setDecision(e.target.value)} placeholder="Run a four-week evening-access pilot"/></label><label>Assumptions to revisit<textarea rows={3} maxLength={3000} value={assumptions} onChange={e=>setAssumptions(e.target.value)}/></label><div className="research-form"><label>Outcome metric and unit<input maxLength={100} value={metric} onChange={e=>setMetric(e.target.value)} placeholder="Paid trial customers"/></label><label>Expected outcome<input type="number" step="any" value={expected} onChange={e=>setExpected(e.target.value)}/></label><label>Review date<input type="date" value={reviewDate} onChange={e=>setReviewDate(e.target.value)}/></label></div><div className="report-actions"><button className="primary" disabled={records.items.length>=100} onClick={create}>Record decision</button><button className="secondary" disabled={!records.items.length} onClick={records.download}>Export decisions</button></div>{error&&<p role="alert">{error}</p>}<p role="status">{records.message}</p>{!records.items.length&&<p className="empty">No decisions recorded yet.</p>}{records.items.map(item=><DecisionRecord key={item.id} item={item} save={next=>records.save(records.items.map(v=>v.id===next.id?next:v))}/>)}</section>;
}
