import type {Report,ScoreKey} from '../types/analysis';
import {scoreLabels} from './ScoringPriorities';

const sources:{key:string;component:ScoreKey;maximum:number}[]=[{key:'maps',component:'competition_gap',maximum:25},{key:'reviews',component:'unmet_need',maximum:25},{key:'trends',component:'demand',maximum:20},{key:'news',component:'market_momentum',maximum:15},{key:'ads',component:'advertising_gap',maximum:15}];
export function freshness(dates:(string|null)[]){
 const valid=dates.filter((d):d is string=>!!d&&Number.isFinite(Date.parse(d))).sort((a,b)=>Date.parse(a)-Date.parse(b));
 return valid.length?`${valid[0].slice(0,10)} to ${valid[valid.length-1].slice(0,10)} (${valid.length}/${dates.length} dated observations)`:'Observation dates unavailable';
}
export function EvidenceStrength({report:r}:{report:Report}){
 const reference=Date.parse(r.methodology.reference_date||r.created_at);
 const recentNews=r.news.filter(n=>n.published_at&&Number.isFinite(Date.parse(n.published_at))&&reference-Date.parse(n.published_at)>=0&&reference-Date.parse(n.published_at)<=90*86400000).length;
 const reviews=r.evidence.filter(e=>e.evidence_type==='reviews');
 const timePoints=r.trend_series.length;
 const mapped=r.competitors.filter(c=>c.latitude!==null&&c.longitude!==null).length;
 const facts:Record<string,{sample:string;coverage:string;fresh:string;improve:string}>={
  maps:{sample:`${r.competitors.length} competitors; ${mapped} mapped`,coverage:`${r.input.city}, ${r.input.country}; first result page only, at most 20 businesses.`,fresh:'Listing update dates unavailable; collection time is shown above.',improve:r.competitors.length?'Check businesses in other neighborhoods directly; this sample is not exhaustive.':'Obtain a nonempty competitor result to earn up to 25 completeness points.'},
  reviews:{sample:`${r.sections.reviews.count} sampled reviews`,coverage:'One recent page each from up to three competitors selected by review count × rating.',fresh:freshness(reviews.map(e=>e.published_at)),improve:r.sections.reviews.count<18?`The 25-point completeness threshold needs at least ${Math.max(0,18-r.sections.reviews.count)} more reviews and all review requests to succeed. More pages are not automatically fetched.`:r.sections.reviews.status!=='complete'?'Resolve failed review requests; all requests must succeed for the 25-point contribution.':'The sample meets the completeness threshold. Validate complaint patterns with direct customer interviews.'},
  trends:{sample:`${timePoints} time points across ${new Set(r.trend_series.flatMap(p=>Object.keys(p.values))).size} keywords`,coverage:`Country-level interest in ${r.input.country}. City wording in keywords does not restrict respondents to that city.`,fresh:timePoints?`Returned period: ${r.trend_series[0].date} to ${r.trend_series[timePoints-1].date}`:'Observation dates unavailable',improve:(r.methodology.confidence_points.trends??0)>0?'Compare search-interest signals with local customer research; relative interest is not sales volume.':'Obtain at least four valid points for one keyword to earn 20 completeness points; consider broader keywords if data is sparse.'},
  news:{sample:`${r.news.length} articles; ${recentNews} within 90 days of analysis`,coverage:`Category/city query, localized to ${r.input.country}; news can discuss broader markets.`,fresh:freshness(r.news.map(n=>n.published_at)),improve:recentNews<5?`At least ${5-recentNews} more dated articles within the analysis’s 90-day window are needed for the 15-point contribution. Verify relevance directly.`:'Verify article context and developments since collection; keyword classification can miss negation.'},
  ads:{sample:`${r.advertising.length} matched creatives`,coverage:'Up to three advertiser searches, worldwide. These are not city-level spending estimates.',fresh:freshness(r.advertising.map(a=>a.last_shown)),improve:(r.methodology.confidence_points.ads??0)>0?'Validate advertiser identity and local reach directly; creative counts do not measure ad spend.':'A reliable matched advertiser active within 30 days of analysis, with all ad requests successful, is needed for 15 completeness points. No match does not imply no advertising.'},
 };
 return <section className="report-section" id="evidence-strength" aria-labelledby="evidence-strength-title"><div className="section-heading"><div><h2 id="evidence-strength-title">Evidence behind every score</h2><p>Collected {new Date(r.created_at).toLocaleString()} · saved confidence {r.confidence_score}/100.</p></div></div>
 <p>Confidence reflects completeness when this report was created. It does not update as evidence ages. These checks explain the saved score; they do not run searches.</p>
 {r.data_mode==='fixture'&&<p className="notice">Synthetic sample: dates and completeness demonstrate the interface, not the strength of real market evidence.</p>}
 <div className="evidence-strength-grid">{sources.map(({key,component,maximum})=>{const f=facts[key],status=r.sections[key].status,points=r.methodology.confidence_points[key]??0;return <article key={key} className="evidence-strength-item"><div className="section-heading"><h3><a href={`#${component}`}>{scoreLabels[component]} · {r.component_scores[component]}/100</a></h3><span className={`status ${status}`}>{status}</span></div><p><strong>{points}/{maximum} confidence points</strong> · {f.sample}</p><dl><dt>Geographic and sample coverage</dt><dd>{f.coverage}</dd><dt>Evidence dates</dt><dd>{f.fresh}</dd><dt>{points===maximum?'What to validate next':'What would improve confidence'}</dt><dd>{f.improve}</dd></dl>{status!=='complete'&&<p className="notice">{r.sections[key].message||'Source incomplete or unavailable; this component uses a neutral fallback where required by the methodology.'}</p>}<a className="hint" href="#methodology">Inspect scoring rules</a></article>})}</div>
 </section>;
}
