import {useMemo,useState} from 'react';
type Category='negative finding'|'implementation failure'|'inconclusive'|'could not reproduce'|'other';
type Failure={id:string;topic:string;method:string;methodVersion:string;dataset:string;setting:string;category:Category;outcome:string;lesson:string;nextStep:string;artifact:string;created:string;updated:string};
type Draft=Omit<Failure,'id'|'created'|'updated'>;
const blank=():Draft=>({topic:'',method:'',methodVersion:'',dataset:'',setting:'',category:'negative finding',outcome:'',lesson:'',nextStep:'',artifact:''});
const tokens=(text:string)=>new Set((text.toLocaleLowerCase().match(/[\p{L}\p{N}]+/gu)||[]).filter(word=>word.length>2));
const similarity=(a:string,b:string)=>{const left=tokens(a),right=tokens(b);if(!left.size||!right.size)return 0;return Math.round(100*[...left].filter(word=>right.has(word)).length/new Set([...left,...right]).size)};
function read(key:string):Failure[]{try{const values=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(values)?values.map((entry:any)=>{const data=entry.data||entry;return {...blank(),...data,id:entry.id||crypto.randomUUID(),created:entry.created||new Date().toISOString(),updated:entry.updated||entry.created||new Date().toISOString(),category:entry.category||'negative finding',topic:data.topic||entry.title||''}}):[]}catch{return []}}
export function FailureKnowledgeNotebook(){
 const key='novelty-shared-failures';const [entries,setEntries]=useState(()=>read(key));const [draft,setDraft]=useState<Draft>(blank());const [editing,setEditing]=useState('');const [search,setSearch]=useState('');const [error,setError]=useState(''),[storageError,setStorageError]=useState(false);
 const persist=(next:Failure[])=>{setEntries(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const saveEntry=()=>{if(!editing&&entries.length>=300){setError('Export and remove older notes before adding another. Existing notes were retained.');return;}if(!draft.topic.trim()||!draft.method.trim()||!draft.outcome.trim()||!draft.lesson.trim()){setError('Topic, method, outcome, and lesson are required.');return}if(draft.artifact){try{const url=new URL(draft.artifact);if(!['https:','http:'].includes(url.protocol))throw new Error()}catch{setError('Use a valid http or https artifact link, or leave it blank.');return}}const now=new Date().toISOString();const existing=entries.find(entry=>entry.id===editing);const entry:Failure={...draft,id:editing||crypto.randomUUID(),created:existing?.created||now,updated:now};persist([entry,...entries.filter(item=>item.id!==entry.id)]);setDraft(blank());setEditing('');setError('')};
 const edit=(entry:Failure)=>{setEditing(entry.id);setDraft({...entry})};
 const remove=(id:string)=>persist(entries.filter(entry=>entry.id!==id));
 const relevant=useMemo(()=>{const query=tokens(search);if(!query.size)return [];return entries.map(entry=>{const text=[entry.topic,entry.method,entry.methodVersion,entry.dataset,entry.setting].join(' ');const terms=[...query].filter(term=>tokens(text).has(term));return {entry,score:similarity(search,text),terms}}).filter(result=>result.score>=15||result.terms.length>=2).sort((a,b)=>b.score-a.score)},[entries,search]);
 const visible=search.trim()?relevant.slice(0,30):entries.slice(0,30).map(entry=>({entry,score:0,terms:[] as string[]}));
 return <>
  <p>Keep failed and inconclusive attempts with their conditions so researchers using this browser can find relevant prior experience. Entries are local to this browser, not shared across team members or devices.</p>
  <div className="tool-input-grid">{([['topic','Research question or topic'],['method','Method or approach'],['methodVersion','Version, settings, or configuration'],['dataset','Dataset or population'],['setting','Experimental setting'],['outcome','What happened'],['nextStep','What should be tried next'],['artifact','Run log or artifact URL']] as const).map(([field,label])=><label key={field}>{label}<input value={draft[field]} onChange={event=>setDraft({...draft,[field]:event.target.value})} maxLength={1800}/></label>)}</div>
  <label>Result category<select value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value as Category})}><option>negative finding</option><option>implementation failure</option><option>inconclusive</option><option>could not reproduce</option><option>other</option></select></label>
  <label>Lesson for the next attempt<textarea rows={3} value={draft.lesson} onChange={event=>setDraft({...draft,lesson:event.target.value})} maxLength={3000}/></label>
  <button type="button" className="quiet-button" onClick={saveEntry}>{editing?'Update failure record':'Save failure record'}</button>{editing&&<button type="button" className="quiet-button" onClick={()=>{setEditing('');setDraft(blank())}}>Cancel edit</button>}{error&&<p className="warning-line" role="alert">{error}</p>}
  <label>Search past attempts by topic, method, dataset, or setting<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Enter the proposed method or dataset"/></label>
  <div className="failure-results">{visible.map(({entry,score,terms})=><article key={entry.id}><header><b>{entry.category} · {entry.topic}</b><span>{search.trim()?score+"% text overlap":""}</span></header><p><b>{entry.method} {entry.methodVersion&&"· "+entry.methodVersion}</b> · {entry.dataset||"dataset not recorded"} · {entry.setting||"setting not recorded"}</p><p>Outcome: {entry.outcome}</p><p>Lesson: {entry.lesson}</p>{entry.nextStep&&<p>Next step: {entry.nextStep}</p>}{terms.length>0&&<small>Matched terms: {terms.join(", ")}</small>}{entry.artifact&&<p><a href={entry.artifact} target="_blank" rel="noreferrer">Open run artifact ↗</a></p>}<small>Recorded {new Date(entry.created).toLocaleDateString()} · updated {new Date(entry.updated).toLocaleDateString()}</small><div><button type="button" className="quiet-button" onClick={()=>edit(entry)}>Edit</button><button type="button" className="quiet-button" onClick={()=>remove(entry.id)}>Delete</button></div></article>)}{search.trim()&&!relevant.length&&<p className="empty-state">No close text matches. This does not mean no related failure exists; try alternate method or dataset terms.</p>}</div>
  {storageError&&<p className="warning-line" role="alert">Failure record could not be saved in browser storage.</p>}
 </>;
}
