import {parseStoredRecord,writeStoredRecord} from '../lib/projectRecords';
import {useResearchDraft} from '../lib/researchDraft';
import {useState} from 'react';
import type {Evidence} from '../types/novelty';
import {AccessMetadataLookup} from './AccessMetadataLookup';
type AccessStatus='candidate found, unverified'|'full text opened and title checked'|'landing page only'|'no copy found';
type Copy={id:string;paperId:string;url:string;host:string;version:string;license:string;status:AccessStatus;checkedAt:string;note:string};
type Draft=Omit<Copy,'id'|'checkedAt'|'paperId'>;
function read(key:string):Copy[]{try{const value=parseStoredRecord(key,'[]');return Array.isArray(value)?value:[]}catch{return []}}
function doiFrom(item:Evidence){const doi=item.details?.doi;if(typeof doi==='string'&&doi)return doi;const match=(item.source_url||'').match(/doi\.org\/(10\.\d{4,9}\/\S+)/i);return match?.[1]?.replace(/[.)]+$/,'')||''}
export function FullTextAccessFinder({reportId,papers}:{reportId:string;papers:Evidence[]}){
 const key='novelty-defense-'+reportId+'-full-text-copies';const [copies,setCopies]=useState(()=>read(key));const [paperId,setPaperId]=useResearchDraft(reportId,'FullTextAccessFinder-paperId','');const [draft,setDraft]=useResearchDraft<Draft>(reportId,'FullTextAccessFinder-draft',{url:'',host:'',version:'author accepted manuscript',license:'',status:'candidate found, unverified',note:''});const [error,setError]=useState(''),[storageError,setStorageError]=useState(false);
 const paper=papers.find(item=>item.id===paperId);const doi=paper?doiFrom(paper):'';const query=paper?'"'+paper.title+'" author manuscript repository':'';
 const persist=(next:Copy[])=>{setCopies(next);try{writeStoredRecord(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const add=()=>{if(!paperId){setError('Select the paper this copy belongs to.');return}if(draft.url.trim()){try{const url=new URL(draft.url);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{setError('Enter a valid http or https URL, or leave it blank when recording that no copy was found.');return}}if(draft.status!=='no copy found'&&!draft.url.trim()){setError('Enter the candidate link before recording an available copy.');return}persist([{...draft,id:crypto.randomUUID(),paperId,url:draft.url.trim(),checkedAt:new Date().toISOString()},...copies].slice(0,150));setDraft({...draft,url:'',host:'',license:'',note:''});setError('')};
 const selectedCopies=copies.filter(copy=>copy.paperId===paperId);
 return <>
  <p>Select a paper and search for an author manuscript or repository copy. Record version and access terms from the host; a working link alone does not establish redistribution rights.</p>
  <label>Paper<select value={paperId} onChange={event=>setPaperId(event.target.value)}><option value="">Choose a paper</option>{papers.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label>
  {paper&&<><div className="tool-link-row">{paper.pdf_url&&<a href={paper.pdf_url} target="_blank" rel="noreferrer">Open returned PDF ↗</a>}{paper.source_url&&<a href={paper.source_url} target="_blank" rel="noreferrer">Open publisher or source page ↗</a>}<a href={'https://scholar.google.com/scholar?q='+encodeURIComponent(query)} target="_blank" rel="noreferrer">Search for author manuscript ↗</a><a href={'https://www.google.com/search?q='+encodeURIComponent(query+' institutional repository OR accepted manuscript')} target="_blank" rel="noreferrer">Search institutional repositories ↗</a>{doi&&<a href={'https://api.openalex.org/works/https://doi.org/'+encodeURIComponent(doi)} target="_blank" rel="noreferrer">Check OpenAlex locations for DOI ↗</a>}</div>
   <details className="fulltext-add"><summary>Record what you found</summary><div className="tool-input-grid"><label>Candidate URL<input value={draft.url} onChange={event=>setDraft({...draft,url:event.target.value})} placeholder="https://repository…"/></label><label>Host or repository<input value={draft.host} onChange={event=>setDraft({...draft,host:event.target.value})}/></label><label>Manuscript version<select value={draft.version} onChange={event=>setDraft({...draft,version:event.target.value})}><option>publisher version</option><option>author accepted manuscript</option><option>preprint</option><option>unknown version</option></select></label><label>License or access terms<input value={draft.license} onChange={event=>setDraft({...draft,license:event.target.value})} placeholder="Copy the terms shown by the host"/></label><label>Check result<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value as AccessStatus})}><option>candidate found, unverified</option><option>full text opened and title checked</option><option>landing page only</option><option>no copy found</option></select></label></div><label>Review note<input value={draft.note} onChange={event=>setDraft({...draft,note:event.target.value})} placeholder="How did you confirm this is the same work?"/></label><button type="button" className="quiet-button" onClick={add}>Save access check</button>{error&&<p className="warning-line" role="alert">{error}</p>}</details>
   <div className="fulltext-copy-list">{selectedCopies.map(copy=><article key={copy.id}><header><b>{copy.host||'Repository not recorded'} · {copy.version}</b><span>{copy.status}</span></header>{copy.url&&<a href={copy.url} target="_blank" rel="noreferrer">Open candidate copy ↗</a>}<p>License/access: {copy.license||'not recorded'} · checked {new Date(copy.checkedAt).toLocaleDateString()}</p>{copy.note&&<small>{copy.note}</small>}<button type="button" className="quiet-button" onClick={()=>persist(copies.filter(item=>item.id!==copy.id))}>Remove record</button></article>)}</div>
  </>}
  {paper&&<AccessMetadataLookup key={paper.id} id={reportId} paperId={paper.id} doi={doi} onCandidate={candidate=>persist([{id:crypto.randomUUID(),paperId:paper.id,url:candidate.url,host:new URL(candidate.url).hostname,version:candidate.version,license:candidate.license,status:'candidate found, unverified',checkedAt:new Date().toISOString(),note:candidate.provider+': '+candidate.availability},...copies])}/>}
  {storageError&&<p className="warning-line" role="alert">The access record could not be saved in this browser.</p>}
  <small>Search links and returned metadata do not guarantee an accessible file. Follow the repository's terms and do not redistribute a copy without permission.</small>
 </>;
}
