import {useState} from 'react';
type Kind='thesis or dissertation'|'preprint'|'technical report'|'standard'|'poster or abstract';
type RecordEntry={id:string;title:string;kind:Kind;url:string;host:string;date:string;datePrecision:'day'|'month'|'year'|'unknown';excerpt:string;query:string;capturedAt:string;review:'unreviewed'|'verified'|'not relevant'};
const kinds:Kind[]=['thesis or dissertation','preprint','technical report','standard','poster or abstract'];
const templates:Record<Kind,(idea:string)=>string>={'thesis or dissertation':idea=>'"'+idea+'" thesis OR dissertation repository','preprint':idea=>'"'+idea+'" preprint arXiv OR OSF','technical report':idea=>'"'+idea+'" "technical report" OR "working paper"','standard':idea=>'"'+idea+'" standard OR specification guideline','poster or abstract':idea=>'"'+idea+'" poster OR conference abstract symposium'};
function read(key:string):RecordEntry[]{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return []}}
export function HiddenPriorWorkDiscovery({reportId,idea}:{reportId:string;idea:string}){
 const key='novelty-defense-'+reportId+'-hidden-prior-work';const [records,setRecords]=useState(()=>read(key));const [draft,setDraft]=useState({title:'',kind:kinds[0] as Kind,url:'',host:'',date:'',datePrecision:'unknown' as RecordEntry['datePrecision'],excerpt:'',query:''});const [error,setError]=useState(''),[storageError,setStorageError]=useState(false);
 const persist=(next:RecordEntry[])=>{setRecords(next);window.dispatchEvent(new CustomEvent('research-prior-work-update',{detail:next}));try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const q=templates[draft.kind](idea);const searchUrl='https://www.google.com/search?q='+encodeURIComponent(q);
 const add=()=>{if(!draft.title.trim()||!draft.url.trim()){setError('A record title and source URL are required so this result can be traced.');return}let parsed:URL;try{parsed=new URL(draft.url)}catch{setError('Enter a valid http or https record URL.');return}if(!['http:','https:'].includes(parsed.protocol)){setError('Only http and https record URLs are supported.');return}if(records.some(record=>record.url===parsed.href)){setError('This source URL is already recorded.');return}persist([{...draft,id:crypto.randomUUID(),title:draft.title.trim(),url:parsed.href,query:draft.query.trim()||q,capturedAt:new Date().toISOString(),review:'unreviewed' as const},...records].slice(0,200));setDraft({...draft,title:'',url:'',host:'',date:'',excerpt:'',query:''});setError('')};
 const update=(id:string,patch:Partial<RecordEntry>)=>persist(records.map(record=>record.id===id?{...record,...patch}:record));
 const remove=(id:string)=>persist(records.filter(record=>record.id!==id));
 return <>
  <p>Search source types that may be absent from paper-only results, then capture provenance so another researcher can find what you reviewed. Searches open in a new tab; copy candidate details here after checking the original record.</p>
  <div className="source-type-searches">{kinds.map(kind=>{const query=templates[kind](idea);return <article key={kind}><b>{kind}</b><span>{query}</span><a href={'https://www.google.com/search?q='+encodeURIComponent(query)} target="_blank" rel="noreferrer">Search this source type ↗</a></article>})}<a href={'https://scholar.google.com/scholar?q='+encodeURIComponent(idea+' thesis dissertation technical report standard') } target="_blank" rel="noreferrer">Search Scholar broadly ↗</a></div>
  <details className="prior-work-add"><summary>Record a candidate you found</summary><div className="tool-input-grid"><label>Title<input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>Source type<select value={draft.kind} onChange={event=>setDraft({...draft,kind:event.target.value as Kind})}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label>Record URL<input value={draft.url} onChange={event=>setDraft({...draft,url:event.target.value})} placeholder="https://…"/></label><label>Repository or host<input value={draft.host} onChange={event=>setDraft({...draft,host:event.target.value})}/></label><label>Publication date<input type={draft.datePrecision==='day'?'date':draft.datePrecision==='month'?'month':'text'} value={draft.date} onChange={event=>setDraft({...draft,date:event.target.value})} placeholder={draft.datePrecision==='year'?'YYYY':''}/></label><label>Date precision<select value={draft.datePrecision} onChange={event=>setDraft({...draft,datePrecision:event.target.value as RecordEntry['datePrecision']})}><option value="unknown">Unknown</option><option value="year">Year</option><option value="month">Month</option><option value="day">Day</option></select></label></div><label>Search query used<input value={draft.query} onChange={event=>setDraft({...draft,query:event.target.value})} placeholder={q}/></label><label>Abstract or relevant passage<textarea rows={3} maxLength={5000} value={draft.excerpt} onChange={event=>setDraft({...draft,excerpt:event.target.value})}/></label><button type="button" className="quiet-button" onClick={add}>Save source record</button>{error&&<p className="warning-line" role="alert">{error}</p>}</details>
  <div className="prior-work-records">{records.map(record=><article key={record.id}><header><span>{record.kind} · {record.host||new URL(record.url).hostname}</span><select value={record.review} onChange={event=>update(record.id,{review:event.target.value as RecordEntry['review']})}><option value="unreviewed">Unreviewed</option><option value="verified">Original record checked</option><option value="not relevant">Not relevant</option></select></header><h4><a href={record.url} target="_blank" rel="noreferrer">{record.title} ↗</a></h4><p>Date: {record.date||'not reported'} · precision: {record.datePrecision} · captured: {new Date(record.capturedAt).toLocaleDateString()}</p>{record.excerpt&&<blockquote>{record.excerpt}</blockquote>}<small>Search: {record.query}</small><button type="button" className="quiet-button" onClick={()=>remove(record.id)}>Remove record</button></article>)}</div>
  {storageError&&<p className="warning-line" role="alert">The prior-work record could not be saved in this browser.</p>}
  <small>External search coverage varies. These recorded results have not been automatically retrieved or independently verified by NoveltyMap.</small>
 </>;
}
