import {parseStoredRecord,writeStoredRecord} from '../lib/projectRecords';
import {useMemo,useState} from 'react';
type Task={id:string;phase:string;title:string;hours:number;cost:number;required:boolean;done:boolean;blocker:string};
type Plan={claimId:string;weeks:number;hoursPerWeek:number;budget:number;currency:string;dataAccess:'ready'|'limited'|'blocked';compute:string;skills:string;experimentName:string;dataset:string;metric:string;threshold:string;tasks:Task[]};
function blank():Plan{return {claimId:'',weeks:8,hoursPerWeek:8,budget:0,currency:'USD',dataAccess:'limited',compute:'',skills:'',experimentName:'',dataset:'',metric:'',threshold:'',tasks:[]}}
function read(key:string):Plan{try{const value=parseStoredRecord(key,'null');return value?{...blank(),...value,tasks:Array.isArray(value.tasks)?value.tasks:[]}:blank()}catch{return blank()}}
function readExperiments(key:string,claimId:string){try{const value=parseStoredRecord(key,'{}');return Array.isArray(value[claimId])?value[claimId]:[]}catch{return []}}
const starter:Omit<Task,'id'>[]=[{phase:'Prerequisite',title:'Confirm permissions and data access',hours:2,cost:0,required:true,done:false,blocker:'Data access is not confirmed'},{phase:'Primary study',title:'Implement and run the primary experiment',hours:12,cost:0,required:true,done:false,blocker:''},{phase:'Primary study',title:'Run the matched baseline comparison',hours:10,cost:0,required:true,done:false,blocker:''},{phase:'Robustness',title:'Run one robustness or sensitivity check',hours:6,cost:0,required:false,done:false,blocker:''},{phase:'Reporting',title:'Record analysis, limitations, and reproducibility details',hours:4,cost:0,required:true,done:false,blocker:''}];
export function MinimumStudyPlanner({reportId,claims}:{reportId:string;claims:{id:string;text:string}[]}){
 const key='novelty-defense-'+reportId+'-study-plan';const [plan,setPlan]=useState(()=>read(key));const [storageError,setStorageError]=useState(false);
 const persist=(next:Plan)=>{setPlan(next);try{writeStoredRecord(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const experiments=readExperiments('novelty-defense-'+reportId+'-measurements',plan.claimId);const selectedExperiment=experiments[0];
 const initialize=()=>{const suggested=selectedExperiment?{experimentName:selectedExperiment.name,dataset:selectedExperiment.dataset,metric:selectedExperiment.metric,threshold:selectedExperiment.threshold}:{};persist({...plan,...suggested,tasks:starter.map(task=>({...task,id:crypto.randomUUID()}))})};
 const updateTask=(id:string,patch:Partial<Task>)=>persist({...plan,tasks:plan.tasks.map(task=>task.id===id?{...task,...patch}:task)});
 const addTask=()=>persist({...plan,tasks:[...plan.tasks,{id:crypto.randomUUID(),phase:'Additional',title:'',hours:1,cost:0,required:false,done:false,blocker:''}]});
 const removeTask=(id:string)=>persist({...plan,tasks:plan.tasks.filter(task=>task.id!==id)});
 const capacity=Math.max(0,plan.weeks)*Math.max(0,plan.hoursPerWeek);const requiredHours=plan.tasks.filter(task=>task.required).reduce((sum,task)=>sum+Math.max(0,task.hours),0);const optionalHours=plan.tasks.filter(task=>!task.required).reduce((sum,task)=>sum+Math.max(0,task.hours),0);const totalCost=plan.tasks.reduce((sum,task)=>sum+Math.max(0,task.cost),0);
 const overCapacity=requiredHours>capacity,overBudget=plan.budget>0&&totalCost>plan.budget;
 const linkedStudy=useMemo(()=>claims.find(claim=>claim.id===plan.claimId),[claims,plan.claimId]);
 const blockers=[!plan.claimId?'Select a central claim.':null,plan.dataAccess==='blocked'?'Data access is blocked.':null,!plan.experimentName?'Primary experiment is unspecified.':null,!plan.dataset?'Dataset or population is unspecified.':null,!plan.metric||!plan.threshold?'Metric or acceptance threshold is missing from the measurement plan.':null,selectedExperiment&&!selectedExperiment.reviewed?'The linked measurement plan has not been reviewed.':null,overCapacity?'Essential task estimates exceed available hours.':null,overBudget?'Estimated task costs exceed budget.':null].filter(Boolean);
 return <>
  <p>Work backward from one claim and a measurable acceptance criterion. Task estimates are editable planning prompts; this tool does not calculate statistical power or promise study credibility.</p>
  <label>Central claim<select value={plan.claimId} onChange={event=>{const next={...plan,claimId:event.target.value};const item=readExperiments('novelty-defense-'+reportId+'-measurements',event.target.value)[0];persist(item?{...next,experimentName:item.name,dataset:item.dataset,metric:item.metric,threshold:item.threshold}:next)}}><option value="">Choose a report claim</option>{claims.map(claim=><option key={claim.id} value={claim.id}>{claim.text}</option>)}</select></label>
  {linkedStudy&&<div className="tool-result"><b>Linked claim</b><p>{linkedStudy.text}</p>{selectedExperiment?<small>Measurement plan: {selectedExperiment.name||'experiment name missing'} · {selectedExperiment.comparator||'comparator missing'} · {selectedExperiment.metric||'metric missing'} · threshold {selectedExperiment.threshold||'missing'}</small>:<small>No experiment is linked to this claim in the measurement alignment feature.</small>}</div>}
  <div className="tool-input-grid"><label>Weeks available<input type="number" min={1} value={plan.weeks} onChange={event=>persist({...plan,weeks:Math.max(1,Number(event.target.value)||1)})}/></label><label>Hours per week<input type="number" min={1} value={plan.hoursPerWeek} onChange={event=>persist({...plan,hoursPerWeek:Math.max(1,Number(event.target.value)||1)})}/></label><label>Budget<input type="number" min={0} value={plan.budget} onChange={event=>persist({...plan,budget:Math.max(0,Number(event.target.value)||0)})}/></label><label>Currency<input value={plan.currency} onChange={event=>persist({...plan,currency:event.target.value.toUpperCase()})} maxLength={5}/></label><label>Data access<select value={plan.dataAccess} onChange={event=>persist({...plan,dataAccess:event.target.value as Plan['dataAccess']})}><option value="ready">Ready</option><option value="limited">Limited</option><option value="blocked">Blocked</option></select></label><label>Compute or equipment required<input value={plan.compute} onChange={event=>persist({...plan,compute:event.target.value})}/></label><label>Skills or collaborators needed<input value={plan.skills} onChange={event=>persist({...plan,skills:event.target.value})}/></label></div>
  <div className="tool-input-grid"><label>Primary experiment<input value={plan.experimentName} onChange={event=>persist({...plan,experimentName:event.target.value})}/></label><label>Dataset or population<input value={plan.dataset} onChange={event=>persist({...plan,dataset:event.target.value})}/></label><label>Primary metric<input value={plan.metric} onChange={event=>persist({...plan,metric:event.target.value})}/></label><label>Acceptance threshold<input value={plan.threshold} onChange={event=>persist({...plan,threshold:event.target.value})}/></label></div>
  <button type="button" className="quiet-button" onClick={initialize}>Create or reset starter study plan</button>
  {plan.tasks.length>0&&<><div className="coverage-strip"><span>Available hours<b>{capacity}</b></span><span>Essential hours<b>{requiredHours}</b></span><span>Optional hours<b>{optionalHours}</b></span><span>Estimated cost<b>{plan.currency} {totalCost}</b></span></div><div className="study-task-list">{plan.tasks.map(task=><article key={task.id}><header><label><input type="checkbox" checked={task.required} onChange={event=>updateTask(task.id,{required:event.target.checked})}/>Essential</label><button type="button" className="quiet-button" onClick={()=>removeTask(task.id)}>Remove task</button></header><div className="tool-input-grid"><label>Phase<input value={task.phase} onChange={event=>updateTask(task.id,{phase:event.target.value})}/></label><label>Task<input value={task.title} onChange={event=>updateTask(task.id,{title:event.target.value})}/></label><label>Estimated hours<input type="number" min={0} value={task.hours} onChange={event=>updateTask(task.id,{hours:Number(event.target.value)})}/></label><label>Estimated cost · {plan.currency}<input type="number" min={0} value={task.cost} onChange={event=>updateTask(task.id,{cost:Number(event.target.value)})}/></label></div><label className="study-blocker">Blocker or dependency<input value={task.blocker} onChange={event=>updateTask(task.id,{blocker:event.target.value})}/></label><label className="study-blocker"><input type="checkbox" checked={task.done} onChange={event=>updateTask(task.id,{done:event.target.checked})}/>Completed</label></article>)}</div><button type="button" className="quiet-button" onClick={addTask}>Add study task</button></>}
  <div className="tool-result"><b>{blockers.length?'Study plan has unresolved blockers':'Study plan assumptions entered'}</b><p>{blockers.length?blockers.join(' '):'Review whether the essential comparisons and outcome measurements are sufficient for this claim.'}</p>{overCapacity&&<small>Reduce optional work first. If essential work still exceeds capacity, narrow the study or increase available time.</small>}{overBudget&&<small>Reduce or source costs explicitly; hours and currency are not combined.</small>}</div>
  {storageError&&<p className="warning-line" role="alert">The study plan could not be saved in this browser.</p>}
 </>;
}
