import {useEffect,useMemo,useState} from 'react';
import type {Evidence} from '../types/novelty';
type Relation='version of'|'extends'|'corrects'|'retracts';
type Edge={id:string;from:string;to:string;relation:Relation;reason:string;confirmedAt:string};
type Saved={edges:Edge[];decisions:Record<string,'rejected'>;representatives:Record<string,string>};
type Prior={id:string;title:string;kind:string;url:string;date:string;excerpt:string;host:string};
const relations:Relation[]=['version of','extends','corrects','retracts'];
const normalized=(text:string)=>text.toLocaleLowerCase().replace(/[^\p{L}\p{N} ]/gu,' ').replace(/\b(a|an|the|of|for|on|in|with|and|study|approach|method)\b/gu,' ').replace(/\s+/g,' ').trim();
const tokens=(text:string)=>new Set(normalized(text).split(' ').filter(word=>word.length>2));
const similarity=(a:string,b:string)=>{const x=tokens(a),y=tokens(b);if(!x.size||!y.size)return 0;return Math.round(100*[...x].filter(word=>y.has(word)).length/new Set([...x,...y]).size)};
function read(key:string):Saved{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value?{edges:Array.isArray(value.edges)?value.edges:[],decisions:value.decisions||{},representatives:value.representatives||{}}:{edges:[],decisions:{},representatives:{}}}catch{return {edges:[],decisions:{},representatives:{}}}}
function readPrior(reportId:string):Evidence[]{try{const items=JSON.parse(localStorage.getItem('novelty-defense-'+reportId+'-hidden-prior-work')||'[]') as Prior[];return (Array.isArray(items)?items:[]).map(item=>({id:'prior:'+item.id,source_type:'web' as const,title:item.title,summary_text:item.excerpt||'',source_url:item.url,publication_date:item.date||undefined,similarity_score:0}))}catch{return []}}
export function PublicationLineageView({reportId,evidence:reportEvidence}:{reportId:string;evidence:Evidence[]}){
 const key='novelty-defense-'+reportId+'-publication-lineage';const [saved,setSaved]=useState(()=>read(key));const [storageError,setStorageError]=useState(false);
 const [priorEvidence,setPriorEvidence]=useState(()=>readPrior(reportId));
 const [manualFrom,setManualFrom]=useState(''),[manualTo,setManualTo]=useState(''),[relation,setRelation]=useState<Relation>('version of'),[reason,setReason]=useState('');
 const evidence=useMemo(()=>[...reportEvidence,...priorEvidence],[reportEvidence,priorEvidence]);
 useEffect(()=>{const listener=(event:Event)=>{const detail=(event as CustomEvent<Prior[]>).detail||[];setPriorEvidence(detail.map(item=>({id:'prior:'+item.id,source_type:'web' as const,title:item.title,summary_text:item.excerpt||'',source_url:item.url,publication_date:item.date||undefined,similarity_score:0})))};window.addEventListener('research-prior-work-update',listener);return()=>window.removeEventListener('research-prior-work-update',listener)},[]);
 const persist=(next:Saved)=>{setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const proposals=useMemo(()=>{const pairs:{a:Evidence;b:Evidence;score:number;authorOverlap:number;key:string}[]=[];for(let i=0;i<evidence.length;i++)for(let j=i+1;j<evidence.length;j++){const a=evidence[i],b=evidence[j];const score=similarity(a.title,b.title);const authorsA=new Set((a.authors||[]).map(name=>name.toLocaleLowerCase())),authorsB=new Set((b.authors||[]).map(name=>name.toLocaleLowerCase()));const authorOverlap=[...authorsA].filter(name=>authorsB.has(name)).length;const pairKey=[a.id,b.id].sort().join('|');if(score>=40||(score>=25&&authorOverlap>0))pairs.push({a,b,score,authorOverlap,key:pairKey})}return pairs.sort((a,b)=>b.score-a.score||b.authorOverlap-a.authorOverlap).slice(0,30)},[evidence]);
 const confirmedPairs=new Set(saved.edges.map(edge=>[edge.from,edge.to].sort().join('|')));
 const candidates=proposals.filter(pair=>!confirmedPairs.has(pair.key)&&!saved.decisions[pair.key]);
 const propose=(from:string,to:string,kind:Relation,why:string)=>{if(!from||!to||from===to)return;const pairKey=[from,to].sort().join('|');const next={...saved,edges:[...saved.edges.filter(edge=>edge.id!==pairKey),{id:pairKey,from,to,relation:kind,reason:why,confirmedAt:new Date().toISOString()}],decisions:{...saved.decisions}};persist(next);setReason('')};
 const removeEdge=(id:string)=>persist({...saved,edges:saved.edges.filter(edge=>edge.id!==id)});
 const dismiss=(pairKey:string)=>persist({...saved,decisions:{...saved.decisions,[pairKey]:'rejected'}});
 const groupEdges=saved.edges.filter(edge=>edge.relation==='version of'||edge.relation==='corrects'||edge.relation==='retracts');
 const parent=new Map(evidence.map(item=>[item.id,item.id]));
 const find=(id:string):string=>{const value=parent.get(id)||id;if(value===id)return id;const root=find(value);parent.set(id,root);return root};
 for(const edge of groupEdges){const from=find(edge.from),to=find(edge.to);if(from!==to)parent.set(from,to)}
 const adjustedRecords=new Set(evidence.map(item=>find(item.id))).size;
 const sourceMap=new Map(evidence.map(item=>[item.id,item]));
 const doi=(item:Evidence)=>String(item.details?.doi||item.details?.DOI||item.source_url||'').replace(/^https?:\/\/(?:dx\.)?doi.org\//i,'').toLowerCase();
 const registered=evidence.flatMap(item=>Object.entries((item.details?.relations||{}) as Record<string,unknown>).flatMap(([label,value])=>/^(is-preprint-of|has-preprint|is-version-of|has-version|is-supplement-to|is-correction-of|is-retraction-of)$/.test(label)&&Array.isArray(value)?value.flatMap((relation:{id?:string})=>{const related=evidence.find(target=>target.id!==item.id&&doi(target)===String(relation.id||'').toLowerCase());if(!related)return [];const pair=[item.id,related.id].sort().join('|');if(confirmedPairs.has(pair)||saved.decisions[pair])return [];return [{from:item,to:related,label,pair}];}):[]));
 const groups=new Map<string,Evidence[]>();for(const item of evidence){const root=find(item.id);groups.set(root,[...(groups.get(root)||[]),item]);}
 return <>
  <p>Similarity only suggests possible relationships. Confirm or reject each proposal after checking identifiers, authors, dates, and the original records. Confirmed links are kept as directed relationships.</p>
  <div className="coverage-strip"><span>Retrieved records<b>{evidence.length}</b></span><span>Confirmed version/correction links<b>{groupEdges.length}</b></span><span>Potential distinct studies after these links<b>{adjustedRecords}</b></span></div>
  {registered.length>0&&<section><h4>Registered metadata relationships</h4>{registered.map((item,index)=><article className="integrity-card" key={item.pair+item.label+index}><p>{item.from.title} → {item.label} → {item.to.title}</p><small>Provider metadata is a candidate relationship; verify its meaning and the original records.</small><button className="quiet-button" onClick={()=>propose(item.from.id,item.to.id,/retract/i.test(item.label)?'retracts':/correct/i.test(item.label)?'corrects':/supplement|part/i.test(item.label)?'extends':'version of','Crossref registered relation '+item.label+'; researcher confirmed')}>Confirm this relationship</button><button className="quiet-button" onClick={()=>dismiss(item.pair)}>Reject relationship</button></article>)}</section>}
  {[...groups].filter(([,items])=>items.length>1).map(([root,items])=><section key={root}><h4>Study version timeline</h4><label>Representative record<select value={saved.representatives[root]||items[0].id} onChange={e=>persist({...saved,representatives:{...saved.representatives,[root]:e.target.value}})}>{items.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><ol>{[...items].sort((a,b)=>(a.publication_date||'9999').localeCompare(b.publication_date||'9999')).map(item=><li key={item.id}>{item.publication_date||'Date unknown'} · {item.title}</li>)}</ol></section>)}
  <details className="lineage-manual"><summary>Add a relationship manually</summary><div className="tool-input-grid"><label>Earlier or source record<select value={manualFrom} onChange={event=>setManualFrom(event.target.value)}><option value="">Choose record</option>{evidence.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Related record<select value={manualTo} onChange={event=>setManualTo(event.target.value)}><option value="">Choose record</option>{evidence.filter(item=>item.id!==manualFrom).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Relationship<select value={relation} onChange={event=>setRelation(event.target.value as Relation)}>{relations.map(value=><option key={value}>{value}</option>)}</select></label><label>Reason and metadata<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="DOI, author, or source evidence"/></label></div><button type="button" className="quiet-button" disabled={!manualFrom||!manualTo} onClick={()=>propose(manualFrom,manualTo,relation,reason)}>Confirm relationship</button></details>
  {candidates.length>0?<div className="lineage-proposals"><h4>Suggested links · inspect before confirming</h4>{candidates.map(({a,b,score,authorOverlap,key:pairKey})=><article key={pairKey}><header><span>Title similarity {score}% · shared authors {authorOverlap}</span><span>Suggestion only</span></header><div className="lineage-pair"><p><b>{a.title}</b><small>{a.publication_date||a.priority_date||'Date not reported'} · {a.authors?.join(', ')||'Authors not reported'} · {a.source_url||'No URL'}</small></p><p><b>{b.title}</b><small>{b.publication_date||b.priority_date||'Date not reported'} · {b.authors?.join(', ')||'Authors not reported'} · {b.source_url||'No URL'}</small></p></div><div className="tool-input-grid"><label>Relationship<select id={'relation-'+pairKey} defaultValue="version of">{relations.map(value=><option key={value}>{value}</option>)}</select></label><label>Review note<input id={'reason-'+pairKey} placeholder="Identifiers or reason"/></label></div><button type="button" className="quiet-button" onClick={()=>{const type=(document.getElementById('relation-'+pairKey) as HTMLSelectElement).value as Relation;const note=(document.getElementById('reason-'+pairKey) as HTMLInputElement).value;propose(a.id,b.id,type,note)}}>Confirm link</button><button type="button" className="quiet-button" onClick={()=>dismiss(pairKey)}>These are separate works</button></article>)}</div>:<p className="empty-state">No unreviewed title-based suggestions. Manually add a relationship when publication metadata shows one.</p>}
  <div className="confirmed-lineages"><h4>Confirmed relationships</h4>{saved.edges.length?saved.edges.map(edge=><article key={edge.id}><p><b>{sourceMap.get(edge.from)?.title||'Source record unavailable'}</b> <span>— {edge.relation} →</span> <b>{sourceMap.get(edge.to)?.title||'Related record unavailable'}</b></p><small>{edge.reason||'No relationship evidence note'} · Confirmed {new Date(edge.confirmedAt).toLocaleDateString()}</small><button type="button" className="quiet-button" onClick={()=>removeEdge(edge.id)}>Remove link</button></article>):<p className="empty-state">No relationships have been confirmed.</p>}</div>
  {storageError&&<p className="warning-line" role="alert">Lineage decisions could not be saved in this browser.</p>}
  <small>The potential distinct-study count collapses only confirmed version, correction, and retraction links. It is an accounting aid; check the source records before citing or counting studies.</small>
 </>;
}
