import {useState} from 'react';
import type {Report} from '../types/analysis';
import type {ResearchInput,ResearchTool} from '../types/research';
import {defaultResearchInput,requestEstimate} from '../lib/researchTools';
export function ResearchInputForm({tool,report,busy,onSubmit}:{tool:ResearchTool;report:Report;busy:boolean;onSubmit:(input:ResearchInput)=>void}){
 const [draft,setDraft]=useState(()=>defaultResearchInput(tool,report));
 const set=(value:Partial<ResearchInput>)=>setDraft({...draft,...value});
 const count=requestEstimate(draft);
 return <form className="extension-form" onSubmit={e=>{e.preventDefault();onSubmit(draft)}}>
 {!['directions','flights'].includes(tool)&&<label>{tool==='scholar'?'Research topic':tool==='jobs'?'Role and location':tool==='shopping'?'Product to compare':tool==='events'?'Event search including location':tool==='hotels'?'Destination or hotel search':'Search phrase'}<input required minLength={3} maxLength={160} value={draft.query||''} onChange={e=>set({query:e.target.value})}/></label>}
 {tool==='directions'&&<><label>Public starting landmark<input required minLength={3} maxLength={160} value={draft.origin||''} onChange={e=>set({origin:e.target.value})}/><span className="hint">Use a public place. Search inputs and route destinations are saved with this public report.</span></label><label>Travel mode<select value={draft.travel_mode} onChange={e=>set({travel_mode:e.target.value})}><option value="walking">Walking</option><option value="transit">Transit</option><option value="driving">Driving</option></select></label><fieldset><legend>Choose up to three destinations</legend>{report.competitors.map(p=><label className="checkbox" key={p.rank}><input type="checkbox" checked={draft.competitor_ranks?.includes(p.rank)||false} disabled={p.latitude===null||p.longitude===null||(!draft.competitor_ranks?.includes(p.rank)&&(draft.competitor_ranks?.length||0)>=3)} onChange={e=>set({competitor_ranks:e.target.checked?[...(draft.competitor_ranks||[]),p.rank]:draft.competitor_ranks?.filter(v=>v!==p.rank)})}/>{p.name}{(p.latitude===null||p.longitude===null)&&' (coordinates unavailable)'}</label>)}</fieldset></>}
 {tool==='hotels'&&<div className="research-form"><label>First check-in (YYYY-MM-DD)<input required pattern="\d{4}-\d{2}-\d{2}" placeholder="YYYY-MM-DD" value={draft.check_in||''} onChange={e=>set({check_in:e.target.value})}/></label><label>First check-out (YYYY-MM-DD)<input required pattern="\d{4}-\d{2}-\d{2}" placeholder="YYYY-MM-DD" value={draft.check_out||''} onChange={e=>set({check_out:e.target.value})}/></label></div>}
 {tool==='flights'&&<div className="research-form"><label>Departure airport (IATA)<input required pattern="[A-Za-z]{3}" maxLength={3} placeholder="DEL" value={draft.departure_airport||''} onChange={e=>set({departure_airport:e.target.value.toUpperCase()})}/></label><label>Arrival airport (IATA)<input required pattern="[A-Za-z]{3}" maxLength={3} placeholder="PNQ" value={draft.arrival_airport||''} onChange={e=>set({arrival_airport:e.target.value.toUpperCase()})}/></label><label>Departure date (YYYY-MM-DD)<input required pattern="\d{4}-\d{2}-\d{2}" placeholder="YYYY-MM-DD" value={draft.departure_date||''} onChange={e=>set({departure_date:e.target.value})}/></label></div>}
 {['hotels','flights'].includes(tool)&&<div className="research-form"><label>Adults<input required type="number" min={1} max={6} step={1} value={draft.adults??''} onChange={e=>set({adults:Number.isFinite(e.target.valueAsNumber)?e.target.valueAsNumber:undefined})}/></label><label>Currency<select value={draft.currency} onChange={e=>set({currency:e.target.value})}>{['INR','USD','EUR','GBP'].map(v=><option key={v}>{v}</option>)}</select></label></div>}
 <label className="checkbox"><input type="checkbox" checked={draft.refresh||false} onChange={e=>set({refresh:e.target.checked})}/>Refresh instead of reusing identical research from the past hour</label>
 <p className="notice">{count} planned {count===1?'search':'searches'} · up to {count*3} provider attempts with retries.{tool==='hotels'&&' Compares your stay with starts 7 and 14 days later.'}{tool==='autocomplete'&&' Searches the phrase, then the “for” and “near” prefixes.'} {report.data_mode==='fixture'?'Fixture mode: zero live requests.':'Requests may consume your search allowance.'}</p>
 <button className="primary" disabled={busy||count===0}>{busy?'A search is running…':'Run this research'}</button><p className="hint">Inputs and results are public. Each source uses a bounded sample without automatic pagination. The displayed data can be incomplete.</p>
 </form>;
}
