import {CopyLink} from './research/CopyLink';
import {useResearchDraft} from '../lib/researchDraft';
import {useMemo,useState} from 'react';
import type {Evidence,NoveltyReport} from '../types/novelty';

const read=(key:string,fallback:any)=>{try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}};
const write=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
const terms=(text:string)=>new Set((text.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>2));
const overlap=(a:string,b:string)=>{const aa=terms(a),bb=terms(b);if(!aa.size||!bb.size)return 0;return Math.round(100*[...aa].filter(x=>bb.has(x)).length/new Set([...aa,...bb]).size)};
const external=(query:string,site='')=>`https://www.google.com/search?q=${encodeURIComponent(`${site} ${query}`.trim())}`;
const safeLink=(value?:string)=>{try{const url=new URL(value||'');return ['http:','https:'].includes(url.protocol)?url.toString():''}catch{return ''}};
const escapeBib=(text:string)=>text.replace(/[{}]/g,'').replace(/\\/g,'');
function citeKey(item:Evidence){return `${(item.authors?.[0]||item.inventors?.[0]||'ResearchScope').split(/[ ,]/)[0]}${(item.publication_date||item.priority_date||'').match(/\d{4}/)?.[0]||'nd'}`.replace(/[^A-Za-z0-9]/g,'')}
function bibtex(items:Evidence[]){return items.map(item=>{
 const type=item.source_type==='patent'?'patent':'article';const year=(item.publication_date||item.priority_date||'').match(/\d{4}/)?.[0]||'unknown';
 const authors=[...(item.authors||[]),...(item.inventors||[])].join(' and ');
 return `@${type}{${citeKey(item)},\n  title = {${escapeBib(item.title)}},\n  author = {${escapeBib(authors||'Unknown')}},\n  year = {${year}},\n  url = {${item.source_url||''}}\n}`
 }).join('\n\n')}
const METHOD_MAP:[string,string[]][]=[['health',['causal inference','external validation','survival analysis','pragmatic trial']],['agriculture',['field validation','domain adaptation','spatial sampling','seasonal ablation']],['machine learning',['data leakage audit','calibration','ablation study','distribution shift']],['education',['quasi-experimental design','longitudinal study','measurement validity','subgroup analysis']],['climate',['scenario analysis','sensitivity analysis','downscaling','uncertainty quantification']]];
const TERM_MAP:Record<string,string[]>={"machine learning":['statistical learning','predictive modeling','pattern recognition'],"deep learning":['neural network','representation learning','foundation model'],"crop disease":['plant pathology','phytopathology','crop health','leaf disease'],"privacy":['data minimization','confidential computing','federated learning'],"low power":['energy efficient','edge computing','resource constrained','embedded inference'],"student":['learner','pupil','undergraduate','school student']};

export function ResearchToolkit({report,id,tool}:{report:NoveltyReport;id:string;tool?:number}){
 const evidence=useMemo(()=>[...report.papers,...report.patents,...report.web_results],[report]);
 const root=`novelty-tools-${id}`;
 const [ideas,setIdeas]=useResearchDraft(id,'ResearchToolkit-ideas','');const [ideaResults,setIdeaResults]=useState<{idea:string;score:number;closest?:Evidence}[]>([]);
 const [weeks,setWeeks]=useResearchDraft(id,'ResearchToolkit-weeks',16),[hours,setHours]=useResearchDraft(id,'ResearchToolkit-hours',8),[dataAccess,setDataAccess]=useResearchDraft(id,'ResearchToolkit-dataAccess',false),[equipment,setEquipment]=useResearchDraft(id,'ResearchToolkit-equipment',false),[skills,setSkills]=useResearchDraft(id,'ResearchToolkit-skills',false);
 const [question,setQuestion]=useResearchDraft(id,'ResearchToolkit-question',{topic:'',population:'',method:'',outcome:'',context:''});
 const [language,setLanguage]=useResearchDraft(id,'ResearchToolkit-language','es'),[translatedQuery,setTranslatedQuery]=useResearchDraft(id,'ResearchToolkit-translatedQuery','');
 const [termQuery,setTermQuery]=useResearchDraft(id,'ResearchToolkit-termQuery',report.input.keywords.slice(0,2).join(' '));
 const [screening,setScreening]=useState<Record<string,{state:string;reason:string}>>(()=>read(`${root}-screening`,{}));
 const [queue,setQueue]=useState<string[]>(()=>read(`${root}-queue`,[]));
 const [checklists,setChecklists]=useState<Record<string,string[]>>(()=>read(`${root}-quality`,{}));
 const [notes,setNotes]=useState<{id:string;text:string;created_at:string;source?:string}[]>(()=>read(`${root}-journal`,[]));
 const [note,setNote]=useResearchDraft(id,'ResearchToolkit-note',''),[noteSource,setNoteSource]=useResearchDraft(id,'ResearchToolkit-noteSource','');
 const [exported,setExported]=useState(false);
 const [methodField,setMethodField]=useResearchDraft(id,'ResearchToolkit-methodField',report.input.field||'');
 const candidateIdeas=ideas.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,5);
 const orderedEvidence=[...evidence].sort((a,b)=>Number(queue.includes(b.id))-Number(queue.includes(a.id))||b.similarity_score-a.similarity_score);
 const ideaChecks=()=>{setIdeaResults(candidateIdeas.map(idea=>{const ranked=[...report.papers,...report.patents].map(item=>({item,score:overlap(idea,item.title+' '+item.summary_text)})).sort((a,b)=>b.score-a.score);return {idea,score:ranked.length?Math.round(ranked.slice(0,3).reduce((n,x)=>n+x.score,0)/Math.min(3,ranked.length)):0,closest:ranked[0]?.item}}))};
 const feasibility=Math.round(100*(Math.min(weeks,52)/52*.25+Math.min(hours,30)/30*.2+(dataAccess?.2:0)+(equipment?.15:0)+(skills?.2:0)));
 const generatedQuestion=[question.topic&&`How does ${question.method||'the proposed approach'} affect ${question.outcome||'the measured outcome'} for ${question.population||'the target population'} in ${question.context||'the chosen setting'}?`].filter(Boolean)[0]||'';
 const methods=METHOD_MAP.find(([field])=>methodField.toLowerCase().includes(field))?.[1]||['causal inference','ablation study','external validation','sensitivity analysis'];
 const synonyms=useMemo(()=>{const found=new Set<string>();for(const [key,values] of Object.entries(TERM_MAP))if(termQuery.toLowerCase().includes(key)){values.forEach(x=>found.add(x))}return [...found]},[termQuery]);
 const retractionUrl=(item:Evidence)=>external(`"${item.title}" (retracted OR correction OR expression of concern)`);
 const qualityItems=['Methods described well enough to assess?','Population or dataset size reported?','A relevant comparator or baseline included?','Limitations stated by the authors?','Code or data available for replication?','Corrections and retraction status checked?'];
 function setDecision(item:Evidence,state:string){const next={...screening,[item.id]:{...screening[item.id],state}};setScreening(next);write(`${root}-screening`,next)}
 function setReason(item:Evidence,reason:string){const next={...screening,[item.id]:{...screening[item.id],reason}};setScreening(next);write(`${root}-screening`,next)}
 function toggleQueue(item:Evidence){const next=queue.includes(item.id)?queue.filter(x=>x!==item.id):[...queue,item.id];setQueue(next);write(`${root}-queue`,next)}
 function toggleQuality(item:Evidence,value:string){const values=checklists[item.id]||[],next={...checklists,[item.id]:values.includes(value)?values.filter(x=>x!==value):[...values,value]};setChecklists(next);write(`${root}-quality`,next)}
 function addNote(){if(note.trim().length<4)return;const next=[{id:crypto.randomUUID(),text:note.trim(),created_at:new Date().toISOString(),source:noteSource.trim()||undefined},...notes].slice(0,100);setNotes(next);write(`${root}-journal`,next);setNote('');setNoteSource('')}
 function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
 function exportBib(){download('researchscope-sources.bib',bibtex(evidence.filter(x=>x.source_type!=='web')),'application/x-bibtex');setExported(true)}
 return <section className="toolkit">
  {tool===undefined&&(<header><p className="kicker">Research toolkit</p><h2>Turn search evidence into project decisions</h2><p>These tools use retrieved snippets and local browser storage. Search links open external sites only when you choose them.</p></header>)}
  {(tool===undefined||tool===1)&&(<details open={tool!==undefined} className="tool-panel"><summary>01 · Compare several project ideas</summary><p>Enter up to five ideas, one per line. Each is compared against the same paper and patent excerpts as this report.</p><textarea aria-label="Project ideas, one per line" rows={4} value={ideas} onChange={e=>setIdeas(e.target.value)} placeholder="Idea 1\nIdea 2"/><button className="quiet-button" disabled={!candidateIdeas.length} onClick={ideaChecks}>Compare ideas</button>{ideaResults.map((x,i)=><article key={i}><b>{x.score}% average text overlap in closest records</b><p>{x.idea}</p>{x.closest&&<small>Closest: {x.closest.title}</small>}</article>)}<small>Use this as a rough comparison; idea quality and feasibility need separate review.</small></details>)}
  {(tool===undefined||tool===2)&&(<details open={tool!==undefined} className="tool-panel"><summary>02 · Check project feasibility</summary><div className="tool-input-grid"><label>Weeks available<input type="number" min={1} max={52} value={weeks} onChange={e=>setWeeks(Math.max(1,Number(e.target.value)))}/></label><label>Hours per week<input type="number" min={1} max={30} value={hours} onChange={e=>setHours(Math.max(1,Number(e.target.value)))}/></label></div><div className="tool-checks">{[['data','Data access',dataAccess,setDataAccess],['equipment','Equipment or compute',equipment,setEquipment],['skills','Required skills',skills,setSkills]].map(([key,label,value,setter])=><label key={String(key)}><input type="checkbox" checked={Boolean(value)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div><p className="tool-result">Planning readiness: <b>{feasibility}/100</b></p><small>Heuristic checklist only; it does not estimate cost, ethics approval, or supervisor availability.</small></details>)}
  {(tool===undefined||tool===3)&&(<details open={tool!==undefined} className="tool-panel"><summary>03 · Find datasets</summary><p>Open targeted searches for datasets matching this topic.</p><div className="tool-link-row">{[['Zenodo','site:zenodo.org '+report.input.title],['Hugging Face','site:huggingface.co/datasets '+report.input.title],['UCI','site:archive.ics.uci.edu '+report.input.title],['Kaggle','site:kaggle.com/datasets '+report.input.title],['Papers with Code','site:paperswithcode.com/datasets '+report.input.title]].map(([name,q])=><a key={name} href={external(q)} target="_blank" rel="noreferrer">Search {name} ↗</a>)}</div><small>Review licenses, provenance, consent, and collection dates at the dataset source.</small></details>)}
  {(tool===undefined||tool===4)&&(<details open={tool!==undefined} className="tool-panel"><summary>04 · Find code and implementations</summary><p>Search repositories and paper-linked implementations using the report title.</p><div className="tool-link-row"><a target="_blank" rel="noreferrer" href={`https://github.com/search?q=${encodeURIComponent(report.input.title)}&type=repositories`}>GitHub repositories ↗</a><a target="_blank" rel="noreferrer" href={external(report.input.title+' implementation code github')}>Web search ↗</a><a target="_blank" rel="noreferrer" href={external(report.input.title+' site:paperswithcode.com')}>Papers with Code ↗</a></div><small>Repository links are search results; inspect licenses, authorship, and maintenance before reuse.</small></details>)}
  {(tool===undefined||tool===5)&&(<details open={tool!==undefined} className="tool-panel"><summary>05 · Explore citation trails</summary><p>Start with a source and follow reference and citing-work searches.</p><ul className="tool-source-list">{report.papers.slice(0,8).map(item=><li key={item.id}><span>{item.title}</span><a target="_blank" rel="noreferrer" href={external(item.title+' cited by references google scholar')}>Trace citations ↗</a>{item.source_url&&<a target="_blank" rel="noreferrer" href={item.source_url}>Open paper ↗</a>}</li>)}</ul><small>This opens citation search pages; ResearchScope does not claim to build a complete citation graph.</small></details>)}
  {(tool===undefined||tool===6)&&(<details open={tool!==undefined} className="tool-panel"><summary>06 · Search for contradictory results</summary><p>Look for replication failures, negative results, and conflicting findings.</p><div className="tool-link-row"><a target="_blank" rel="noreferrer" href={external(`"${report.input.title}" conflicting results replication failure`)}>Search conflicting results ↗</a><a target="_blank" rel="noreferrer" href={external(`"${report.input.title}" null results failed to replicate`)}>Search failed replications ↗</a><a target="_blank" rel="noreferrer" href={external(`"${report.input.title}" limitations counter evidence`)}>Search limitations ↗</a></div><small>Search wording can miss disagreement; inspect original studies and methods.</small></details>)}
  {(tool===undefined||tool===7)&&(<details open={tool!==undefined} className="tool-panel"><summary>07 · Check corrections and retractions</summary><p>Search publication records before relying on a paper.</p><ul className="tool-source-list">{report.papers.slice(0,8).map(item=><li key={item.id}><span>{item.title}</span><a target="_blank" rel="noreferrer" href={retractionUrl(item)}>Search status ↗</a><a target="_blank" rel="noreferrer" href={`https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(item.title+' retracted')}`}>PubMed ↗</a></li>)}</ul><small>These are lookup links, not a verified retraction status.</small></details>)}
  {(tool===undefined||tool===8)&&(<details open={tool!==undefined} className="tool-panel"><summary>08 · Assess study quality</summary><p>Mark what you verified in the original full text. Checks are saved in this browser.</p>{report.papers.slice(0,8).map(item=><article className="quality-card" key={item.id}><b>{item.title}</b>{qualityItems.map(q=><label key={q}><input type="checkbox" checked={(checklists[item.id]||[]).includes(q)} onChange={()=>toggleQuality(item,q)}/>{q}</label>)}<small>Researcher assessment; not an automated quality score.</small></article>)}</details>)}
  {(tool===undefined||tool===9)&&(<details open={tool!==undefined} className="tool-panel"><summary>09 · Expand terminology</summary><label>Search phrases<input value={termQuery} onChange={e=>setTermQuery(e.target.value)}/></label><div className="term-chips">{synonyms.length?synonyms.map(x=><button key={x} onClick={()=>setTermQuery(termQuery+', '+x)}>{x} +</button>):<small>Add a topic with known aliases (for example “crop disease” or “privacy”).</small>}</div><small>Suggested vocabulary is a small editable glossary, not an exhaustive thesaurus.</small></details>)}
  {(tool===undefined||tool===10)&&(<details open={tool!==undefined} className="tool-panel"><summary>10 · Search in another language</summary><p>Translate a search phrase, review the translation, then search Scholar in that language.</p><label>Phrase to translate<input value={translatedQuery||report.input.title} onChange={e=>setTranslatedQuery(e.target.value)}/></label><label>Target language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="es">Spanish</option><option value="hi">Hindi</option><option value="zh-CN">Chinese (simplified)</option><option value="fr">French</option><option value="de">German</option><option value="ja">Japanese</option><option value="pt">Portuguese</option></select></label><div className="tool-link-row"><a target="_blank" rel="noreferrer" href={`https://translate.google.com/?sl=auto&tl=${language}&text=${encodeURIComponent(translatedQuery||report.input.title)}&op=translate`}>Review translation ↗</a><a target="_blank" rel="noreferrer" href={`https://scholar.google.com/scholar?q=${encodeURIComponent(translatedQuery||report.input.title)}`}>Search Scholar ↗</a></div><small>Check translated terms with a fluent reader where terminology matters.</small></details>)}
  {(tool===undefined||tool===11)&&(<details open={tool!==undefined} className="tool-panel"><summary>11 · Find methods from neighboring fields</summary><label>Research field or method<input value={methodField} onChange={e=>setMethodField(e.target.value)}/></label><p>Possible methods to investigate:</p><div className="term-chips">{methods.map(method=><a key={method} target="_blank" rel="noreferrer" href={external(`${report.input.title} ${method}`)}>{method} ↗</a>)}</div><small>These prompts come from a small field map and need domain expert review.</small></details>)}
  {(tool===undefined||tool===12)&&(<details open={tool!==undefined} className="tool-panel"><summary>12 · Shape a research question</summary><div className="tool-input-grid">{(['topic','population','method','outcome','context'] as const).map(key=><label key={key}>{key}<input value={question[key]} onChange={e=>setQuestion({...question,[key]:e.target.value})}/></label>)}</div>{generatedQuestion&&<article className="tool-result"><b>Draft question</b><p>{generatedQuestion}</p><CopyLink value={generatedQuestion} label="Copy question" copiedMessage="Question copied." fallbackLabel="Question to copy"/></article>}</details>)}
  {(tool===undefined||tool===13)&&(<details open={tool!==undefined} className="tool-panel"><summary>13 · Check search sensitivity</summary><p>Compare score contribution by source to see whether your conclusion depends on one source type.</p><div className="sensitivity-bars">{(['scholar','patent','web'] as const).map(type=>{const values=evidence.filter(x=>x.source_type===type).map(x=>x.similarity_score).sort((a,b)=>b-a),score=values.length?Math.round(values[0]*.5+(values.slice(0,5).reduce((a,b)=>a+b,0)/Math.min(5,values.length))*.3+Math.min(values.filter(x=>x>=60).length/5,1)*20):0;return <div key={type}><span>{type} · {values.length} records · {score}</span><i style={{width:`${score}%`}}/></div>})}</div><small>These source-only scores apply the report formula to each slice. Compare them as a diagnostic, not separate novelty verdicts.</small></details>)}
  {(tool===undefined||tool===14)&&(<details open={tool!==undefined} className="tool-panel"><summary>14 · Verify citation details</summary><p>Crossref can search metadata for a title. Compare the result to the source record before exporting.</p><ul className="tool-source-list">{report.papers.slice(0,8).map(item=><li key={item.id}><span>{item.title}</span><a target="_blank" rel="noreferrer" href={`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(item.title)}&rows=3`}>Check Crossref ↗</a><a target="_blank" rel="noreferrer" href={`https://scholar.google.com/scholar?q=${encodeURIComponent(item.title)}`}>Compare Scholar ↗</a></li>)}</ul><small>Search results do not confirm metadata automatically; verify DOI, authors, and publication year.</small></details>)}
  {(tool===undefined||tool===15)&&(<details open={tool!==undefined} className="tool-panel"><summary>15 · Export references</summary><p>Download paper and patent records as a BibTeX file for your reference manager.</p><button className="quiet-button" disabled={!report.papers.length&&!report.patents.length} onClick={exportBib}>Download BibTeX</button>{exported&&<p role="status">Export created. Review each entry before citing it.</p>}</details>)}
  {(tool===undefined||tool===16)&&(<details open={tool!==undefined} className="tool-panel"><summary>16 · Screen retrieved records</summary><p>Record include, exclude, or maybe decisions with a reason. Stored locally in this browser.</p>{evidence.map(item=><article className="screen-card" key={item.id}><b>{item.title}</b><small>{item.source_type} · {item.similarity_score}% overlap</small><div className="tool-link-row">{['include','exclude','maybe'].map(state=><button key={state} className={screening[item.id]?.state===state?'selected':''} onClick={()=>setDecision(item,state)}>{state}</button>)}</div><input aria-label={`Reason for ${item.title}`} placeholder="Reason for decision" value={screening[item.id]?.reason||''} onChange={e=>setReason(item,e.target.value)}/></article>)}</details>)}
  {(tool===undefined||tool===17)&&(<details open={tool!==undefined} className="tool-panel"><summary>17 · Build a reading queue <span className="count">{queue.length}</span></summary><p>Queued records sort to the top and remain saved in this browser.</p>{orderedEvidence.map(item=><label className="queue-row" key={item.id}><input type="checkbox" checked={queue.includes(item.id)} onChange={()=>toggleQueue(item)}/><span>{item.title}<small>{item.source_type} · match {item.similarity_score}%{item.citation_count!=null?` · cited ${item.citation_count}`:''}</small></span><a href={item.source_url||'#'} target="_blank" rel="noreferrer">Open</a></label>)}</details>)}
  {(tool===undefined||tool===18)&&(<details open={tool!==undefined} className="tool-panel"><summary>18 · Reproducibility checklist</summary><p>Track details to verify for each close paper before attempting reproduction.</p>{report.papers.slice(0,8).map(item=><article className="quality-card" key={item.id}><b>{item.title}</b>{['Exact dataset/version recorded','Code and dependencies recorded','Model and training parameters recorded','Baseline conditions recorded','Metric calculation recorded','Hardware and random seeds recorded'].map(q=><label key={q}><input type="checkbox" checked={(checklists[item.id]||[]).includes(q)} onChange={()=>toggleQuality(item,q)}/>{q}</label>)}</article>)}</details>)}
  {(tool===undefined||tool===19)&&(<details open={tool!==undefined} className="tool-panel"><summary>19 · Keep a research decision journal</summary><p>Notes stay in this browser. Add a short decision and optionally link its evidence.</p><textarea aria-label="Research decision and reason" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Decision, reason, and what evidence would change it"/><input aria-label="Decision evidence source URL" value={noteSource} onChange={e=>setNoteSource(e.target.value)} placeholder="Optional source URL"/><button className="quiet-button" disabled={note.trim().length<4} onClick={addNote}>Save decision</button>{notes.map(x=><article key={x.id}><small>{new Date(x.created_at).toLocaleString()}</small><p>{x.text}</p>{safeLink(x.source)&&<a href={safeLink(x.source)} target="_blank" rel="noreferrer">Evidence link ↗</a>}</article>)}</details>)}
  {(tool===undefined||tool===20)&&(<details open={tool!==undefined} className="tool-panel"><summary>20 · Private local research mode</summary><p>Use the separate local workspace to compare a draft against text notes on this device. It sends nothing to ResearchScope servers and does not search the web.</p><a className="quiet-button" href="/research-scope/private">Open local workspace ↗</a></details>)}
 </section>
}
