import {useMemo,useState} from 'react';
import type {Evidence} from '../types/novelty';
import {dependencyProblem} from '../lib/researchReview';
type Status='open'|'in progress'|'blocked'|'done';
type Task={id:string;title:string;owner:string;due:string;claimId:string;experiment:string;evidenceIds:string[];evidenceUrl:string;completionNote:string;status:Status;blocker:string;dependsOn:string[];createdAt:string;updatedAt:string;history:{date:string;change:string}[]};
type Draft=Pick<Task,'title'|'owner'|'due'|'claimId'|'experiment'|'evidenceIds'|'evidenceUrl'|'completionNote'|'blocker'|'dependsOn'>;
const blank=():Draft=>({title:'',owner:'',due:'',claimId:'',experiment:'',evidenceIds:[],evidenceUrl:'',completionNote:'',blocker:'',dependsOn:[]});
const statuses:Status[]=['open','in progress','blocked','done'];
function read(key:string):Task[]{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value.map((raw:any)=>{const data=raw.data||raw;return {...blank(),...data,id:raw.id||crypto.randomUUID(),title:data.title||raw.title||'',status:statuses.includes(data.status)?data.status:'open',createdAt:raw.createdAt||raw.created||new Date().toISOString(),updatedAt:raw.updatedAt||raw.created||new Date().toISOString(),history:Array.isArray(raw.history)?raw.history:[],evidenceIds:Array.isArray(data.evidenceIds)?data.evidenceIds:[],dependsOn:Array.isArray(data.dependsOn)?data.dependsOn:[]}}):[]}catch{return []}}
function exportTasks(tasks:Task[]){const rows=[['task','owner','due','status','claim','experiment','evidence IDs','evidence URL','completion evidence','blocker','dependencies'],...tasks.map(task=>[task.title,task.owner,task.due,task.status,task.claimId,task.experiment,task.evidenceIds.join('; '),task.evidenceUrl,task.completionNote,task.blocker,task.dependsOn.join('; ')])];const text=rows.map(row=>row.map(value=>'"'+value.replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='research-task-board.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function ResearchTaskBoard({reportId,claims,evidence}:{reportId:string;claims:{id:string;text:string}[];evidence:Evidence[]}){
 const key='novelty-defense-'+reportId+'-tasks';const [tasks,setTasks]=useState(()=>read(key));const [draft,setDraft]=useState<Draft>(blank());const [statusFilter,setStatusFilter]=useState('all');const [editing,setEditing]=useState('');const [storageError,setStorageError]=useState(false),[error,setError]=useState('');
 const persist=(next:Task[])=>{setTasks(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const claimMap=new Map(claims.map(claim=>[claim.id,claim.text]));const evidenceMap=new Map(evidence.map(item=>[item.id,item.title]));
 const board=useMemo(()=>tasks.filter(task=>statusFilter==='all'||task.status===statusFilter).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')),[tasks,statusFilter]);
 const overdue=tasks.filter(task=>task.due&&task.due<new Date().toISOString().slice(0,10)&&task.status!=='done').length;
 const saveTask=()=>{
  if(!draft.title.trim()){setError('Add a task title.');return}
  if(draft.evidenceUrl){try{const url=new URL(draft.evidenceUrl);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{setError('Evidence links must use http or https.');return}}
  const now=new Date().toISOString(),existing=tasks.find(task=>task.id===editing);
  const problem=dependencyProblem(tasks,editing||'new-task',draft.dependsOn);if(problem){setError(problem);return;}
  if(existing?.status==='done'&&draft.dependsOn.some(id=>tasks.find(item=>item.id===id)?.status!=='done')){setError('A completed task cannot acquire unfinished dependencies. Reopen it first.');return;}
  if(existing?.status==='done'&&!draft.completionNote.trim()&&!draft.evidenceUrl.trim()&&!draft.evidenceIds.length){setError('Keep completion evidence attached before saving a completed task.');return}
  const task:Task={...draft,id:editing||crypto.randomUUID(),status:existing?.status||'open',createdAt:existing?.createdAt||now,updatedAt:now,history:[...(existing?.history||[]),{date:now,change:editing?'Task details updated':'Task created'}]};
  persist([task,...tasks.filter(item=>item.id!==task.id)]);setDraft(blank());setEditing('');setError('');
 };
 const edit=(task:Task)=>{setEditing(task.id);setDraft({...task})};
 const updateStatus=(task:Task,status:Status)=>{if(status==='done'&&task.dependsOn.some(id=>tasks.find(item=>item.id===id)?.status!=='done')){setError('Complete every dependency before marking this task done.');return}if(status==='done'&&!task.completionNote.trim()&&!task.evidenceUrl.trim()&&!task.evidenceIds.length){setError('Add completion evidence before marking this task done.');return}if(status==='blocked'&&!task.blocker.trim()){setError('Record the blocker before using the blocked status.');return}const now=new Date().toISOString();persist(tasks.map(item=>item.id===task.id?{...item,status,updatedAt:now,history:[...item.history,{date:now,change:'Status set to '+status}]}:item));setError('')};
 const remove=(id:string)=>{if(tasks.some(task=>task.dependsOn.includes(id))){setError('Remove this task from dependent tasks before deleting it.');return;}persist(tasks.filter(task=>task.id!==id));};
 return <>
  <p>Assign review work and experiments to your team. This version saves to the current browser only; names are labels entered by the researcher and are not verified identities.</p>
  <div className="task-board-counts"><span>Open <b>{tasks.filter(task=>task.status==='open').length}</b></span><span>In progress <b>{tasks.filter(task=>task.status==='in progress').length}</b></span><span>Blocked <b>{tasks.filter(task=>task.status==='blocked').length}</b></span><span>Overdue <b>{overdue}</b></span></div>
  <details className="task-editor" open={!tasks.length||Boolean(editing)}><summary>{editing?'Edit task':'Add a research task'}</summary><div className="tool-input-grid"><label>Task<input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>Owner<input value={draft.owner} onChange={event=>setDraft({...draft,owner:event.target.value})} placeholder="Team member name"/></label><label>Due date<input type="date" value={draft.due} onChange={event=>setDraft({...draft,due:event.target.value})}/></label><label>Related claim<select value={draft.claimId} onChange={event=>setDraft({...draft,claimId:event.target.value})}><option value="">General research check</option>{claims.map(claim=><option key={claim.id} value={claim.id}>{claim.text}</option>)}</select></label><label>Experiment or verification step<input value={draft.experiment} onChange={event=>setDraft({...draft,experiment:event.target.value})}/></label></div><p>Supporting sources</p><div className="defense-checks">{evidence.map(item=><label key={item.id}><input type="checkbox" checked={draft.evidenceIds.includes(item.id)} onChange={event=>setDraft({...draft,evidenceIds:event.target.checked?[...new Set([...draft.evidenceIds,item.id])]:draft.evidenceIds.filter(id=>id!==item.id)})}/>{item.title}</label>)}</div><div className="tool-input-grid"><label>Evidence URL<input value={draft.evidenceUrl} onChange={event=>setDraft({...draft,evidenceUrl:event.target.value})} placeholder="Protocol, run log, or verification artifact"/></label><label>Dependencies<select multiple value={draft.dependsOn} onChange={event=>setDraft({...draft,dependsOn:[...event.target.selectedOptions].map(option=>option.value)})}>{tasks.filter(task=>task.id!==editing).map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select></label></div><label>Completion evidence or note<textarea rows={2} value={draft.completionNote} onChange={event=>setDraft({...draft,completionNote:event.target.value})} placeholder="What must be recorded to count this as done?"/></label><label>Blocker details<input value={draft.blocker} onChange={event=>setDraft({...draft,blocker:event.target.value})}/></label><button type="button" className="quiet-button" onClick={saveTask}>{editing?'Save task changes':'Add task'}</button>{editing&&<button type="button" className="quiet-button" onClick={()=>{setEditing('');setDraft(blank())}}>Cancel</button>}</details>
  {error&&<p className="warning-line" role="alert">{error}</p>}
  <div className="task-board-tools"><label>Show<select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="all">All tasks</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><button type="button" className="quiet-button" disabled={!tasks.length} onClick={()=>exportTasks(tasks)}>Export board CSV</button></div>
  <div className="task-board-list">{board.map(task=><article key={task.id}><header><b>{task.title}</b><select aria-label={`Status for ${task.title}`} value={task.status} onChange={event=>updateStatus(task,event.target.value as Status)}>{statuses.map(status=><option key={status} disabled={status==='done'&&!task.completionNote.trim()&&!task.evidenceUrl.trim()&&!task.evidenceIds.length}>{status}</option>)}</select></header><small>{task.owner||'Unassigned'} · due {task.due||'not set'} · {claimMap.get(task.claimId)||'General check'}</small>{task.experiment&&<p>Experiment: {task.experiment}</p>}{task.blocker&&task.status==='blocked'&&<p className="warning-line">Blocked: {task.blocker}</p>}{task.dependsOn.length>0&&<p>Depends on: {task.dependsOn.map(id=>tasks.find(item=>item.id===id)?.title||'removed task').join(', ')}</p>}{task.evidenceIds.map(id=><small key={id}>Source: {evidenceMap.get(id)||'source record unavailable'}<br/></small>)}{task.evidenceUrl&&<p><a href={task.evidenceUrl} target="_blank" rel="noreferrer">Open completion artifact ↗</a></p>}{task.completionNote&&<p>Completion evidence: {task.completionNote}</p>}<details className="task-history"><summary>Change history · {task.history.length}</summary>{task.history.map((change,index)=><small key={index}>{new Date(change.date).toLocaleString()} · {change.change}<br/></small>)}</details><small>Updated {new Date(task.updatedAt).toLocaleString()}</small><div><button type="button" className="quiet-button" onClick={()=>edit(task)}>Edit</button><button type="button" className="quiet-button" onClick={()=>remove(task.id)}>Remove</button></div></article>)}{!board.length&&<p className="empty-state">No tasks in this view. Add an owner and due date to make the next verification step clear.</p>}</div>
  {storageError&&<p className="warning-line" role="alert">Task board could not be saved in this browser.</p>}
 </>;
}
