import {useState} from 'react';
type Round={id:string;date:string;sourceType:string;query:string;identifiers:string[];notes:string;legacyCount?:number};
type Saved={rounds:Round[];openGaps:string[];allRequiredTypesSearched:boolean;minimumRounds:number;lowYieldLimit:number};
const blank=():Saved=>({rounds:[],openGaps:[],allRequiredTypesSearched:false,minimumRounds:3,lowYieldLimit:0});
function read(key:string):Saved{try{const value=JSON.parse(localStorage.getItem(key)||'null');if(!value)return blank();return {...blank(),...value,rounds:Array.isArray(value.rounds)?value.rounds.map((round:any)=>({id:round.id||crypto.randomUUID(),date:round.date||round.created||new Date().toISOString(),sourceType:round.sourceType||'Previously recorded round',query:round.query||round.title||'Previous manually recorded count',identifiers:Array.isArray(round.identifiers)?round.identifiers:[],notes:round.notes||'',legacyCount:Array.isArray(round.identifiers)?undefined:Number(round.data?.new_records)})):[]}}catch{return blank()}}
const normalize=(value:string)=>value.trim().toLocaleLowerCase().replace(/\s+/g,' ');
export function SearchStoppingAssistant({reportId}:{reportId:string}){
 const key='novelty-defense-'+reportId+'-rounds';const [saved,setSaved]=useState(()=>read(key));const [draft,setDraft]=useState({sourceType:'Academic index',query:'',identifiers:'',notes:''});const [storageError,setStorageError]=useState(false);
 const persist=(next:Saved)=>{setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const allPrevious=new Set<string>();const roundStats=saved.rounds.map(round=>{const ids=[...new Set(round.identifiers.map(normalize).filter(Boolean))];const newIds=ids.filter(id=>!allPrevious.has(id));ids.forEach(id=>allPrevious.add(id));return {round,ids,newIds,count:round.legacyCount??newIds.length}});
 const gaps=saved.openGaps.filter(Boolean);
 const reliableRounds=roundStats.filter(item=>item.round.legacyCount===undefined);
 const recentRounds=roundStats.slice(-2);
 const suggestedStop=reliableRounds.length>=saved.minimumRounds&&recentRounds.length===2&&recentRounds.every(item=>item.round.legacyCount===undefined&&item.newIds.length<=saved.lowYieldLimit)&&gaps.length===0&&saved.allRequiredTypesSearched;
 const trend=roundStats.map((item,index)=>({label:'Round '+(index+1),newCount:item.count,total:item.ids.length,estimated:item.round.legacyCount!==undefined}));
 const addRound=()=>{const identifiers=draft.identifiers.split(/[\n,;]/).map(normalize).filter(Boolean);if(!draft.query.trim())return;const next={...saved,rounds:[...saved.rounds,{id:crypto.randomUUID(),date:new Date().toISOString(),sourceType:draft.sourceType,query:draft.query.trim(),identifiers:[...new Set(identifiers)],notes:draft.notes.trim()}].slice(-40)};persist(next);setDraft({...draft,query:'',identifiers:'',notes:''})};
 const updateGap=(index:number,value:string)=>{const openGaps=[...saved.openGaps];openGaps[index]=value;persist({...saved,openGaps})};
 const addGap=()=>persist({...saved,openGaps:[...saved.openGaps,'']});
 const removeGap=(index:number)=>persist({...saved,openGaps:saved.openGaps.filter((_,i)=>i!==index)});
 const lastAdvisory=!roundStats.length?'Record search rounds and identify the unresolved source types or claims.':suggestedStop?'Low yield across recent rounds and no recorded coverage gaps. Review the actual queries and decide whether the remaining uncertainty is acceptable.':gaps.length?('Continue or revise: resolve '+gaps.length+' recorded coverage gap(s), even if search yield is low.'):!saved.allRequiredTypesSearched?'Coverage is not confirmed. Search must-check source types before treating low yield as a stopping signal.':reliableRounds.length<saved.minimumRounds?'Keep searching until the minimum number of rounds with identifiers is recorded, then review their yield.':'Yield is still above your threshold in at least one recent round. Run a focused follow-up or document why it is unnecessary.';
 return <>
  <p>Log each completed search round. Add one DOI, URL, or stable title per relevant source; later rounds count only identifiers not already recorded. The stopping suggestion follows your recorded criteria and still needs researcher judgment.</p>
  <div className="tool-input-grid"><label>Source or index<input value={draft.sourceType} onChange={event=>setDraft({...draft,sourceType:event.target.value})} placeholder="e.g. thesis repositories"/></label><label>Query used<input value={draft.query} onChange={event=>setDraft({...draft,query:event.target.value})}/></label></div>
  <label>Relevant unique record identifiers<textarea rows={4} value={draft.identifiers} onChange={event=>setDraft({...draft,identifiers:event.target.value})} placeholder={'One DOI, source URL, or stable title per line; leave blank if none were found'}/></label><label>Search notes<input value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><button type="button" className="quiet-button" disabled={!draft.query.trim()} onClick={addRound}>Record completed search round</button>
  <div className="tool-input-grid"><label>Minimum rounds<input type="number" min={1} max={30} value={saved.minimumRounds} onChange={event=>persist({...saved,minimumRounds:Math.min(30,Math.max(1,Number(event.target.value)||1))})}/></label><label>Low yield threshold · new unique records<input type="number" min={0} value={saved.lowYieldLimit} onChange={event=>persist({...saved,lowYieldLimit:Math.max(0,Number(event.target.value)||0)})}/></label></div>
  <div className="defense-checks"><label><input type="checkbox" checked={saved.allRequiredTypesSearched} onChange={event=>persist({...saved,allRequiredTypesSearched:event.target.checked})}/>I reviewed the scope and searched all source types required for this project.</label></div>
  <section className="search-gaps"><h4>Unresolved coverage gaps</h4><p>Record source types, claims, date ranges, or languages still needing review.</p>{saved.openGaps.map((gap,index)=><div key={index}><input value={gap} onChange={event=>updateGap(index,event.target.value)} placeholder="e.g. non-English dissertation repositories"/><button type="button" className="quiet-button" onClick={()=>removeGap(index)}>Remove</button></div>)}<button type="button" className="quiet-button" onClick={addGap}>Add coverage gap</button></section>
  <div className="search-yield-chart" aria-label="New unique relevant records per search round">{trend.map((item,index)=><article key={index}><span>{item.label}</span><b>{item.newCount}</b><small>{item.estimated?'older manual estimate':'new unique · '+item.total+' relevant IDs logged'}</small></article>)}</div>
  {roundStats.length>0&&<div className="search-round-list">{roundStats.map(({round,newIds},index)=><article key={round.id}><header><b>Round {index+1} · {round.sourceType}</b><small>{new Date(round.date).toLocaleDateString()}</small></header><p>{round.query}</p><small>{round.legacyCount===undefined?newIds.length+' unique new record(s) · '+round.identifiers.length+' relevant identifiers recorded':round.legacyCount+' manually counted new records · identifiers were not retained, so excluded from unique-yield advice'}</small>{round.notes&&<p>{round.notes}</p>}</article>)}</div>}
  <div className="tool-result"><b>{suggestedStop?'Possible stopping point':'Keep searching or revise the search plan'}</b><p>{lastAdvisory}</p><small>Compare the counts with actual source coverage and relevance. A zero-yield round alone is not evidence that the literature is complete.</small></div>
  {storageError&&<p className="warning-line" role="alert">Search-round history could not be saved in this browser.</p>}
 </>;
}
