import {useState} from 'react';
import {z} from 'zod';
import type {Report} from '../types/analysis';
import {useLocalRecords} from '../lib/useLocalRecords';
import {outcome} from '../lib/exploration';
const count=z.number().int().min(0).max(10000);
export const experimentSchema=z.object({id:z.string(),created:z.string(),hypothesis:z.string().trim().min(5).max(1000),segment:z.string().trim().min(2).max(200),target:count.min(1),required:count.min(1),completed:count,positive:count,notes:z.string().max(5000),baseline:z.number(),interpretation:z.string()}).refine(v=>v.required<=v.target&&v.positive<=v.completed);
type Experiment=z.infer<typeof experimentSchema>;
function Results({item,save}:{item:Experiment;save:(v:Experiment)=>boolean}){
 const [completed,setCompleted]=useState(item.completed),[positive,setPositive]=useState(item.positive),[notes,setNotes]=useState(item.notes),[status,setStatus]=useState('');
 function update(){const next={...item,completed,positive,notes};if(!experimentSchema.safeParse(next).success){setStatus('Enter whole response counts; supporting responses cannot exceed total responses.');return}if(save(next))setStatus('Results saved');else setStatus('Could not save results; keep this tab open.')}
 return <details className="research-record"><summary>{item.hypothesis}</summary><p>Created {item.created.slice(0,10)} · {item.segment}</p><p>Plan: at least {item.required} of {item.target} responses ({(item.required/item.target*100).toFixed(0)}%) support the hypothesis. If you collect more responses, the same percentage applies.</p><p>Original report: {item.baseline}/100 · {item.interpretation}. This experiment tests a specific hypothesis, not the entire score.</p><div className="research-form"><label>Total responses<input type="number" min={0} max={10000} step={1} value={completed} onChange={e=>setCompleted(e.target.valueAsNumber)}/></label><label>Supporting responses<input type="number" min={0} max={10000} step={1} value={positive} onChange={e=>setPositive(e.target.valueAsNumber)}/></label></div><label>Findings and contradictory evidence<textarea rows={3} maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="secondary" onClick={update}>Save experiment results</button><p role="status">{status}</p><p><strong>Saved outcome: {outcome(item.target,item.required,item.completed,item.positive)}</strong></p><p>Use responses about actual past behavior. Avoid collecting names or personal contact details here.</p></details>;
}
export function ValidationLab({report}:{report:Report}){
 const records=useLocalRecords('market-experiments-v1:'+report.id,experimentSchema);
 const topic=report.review_topics.find(t=>t.repeated)?.topic||'the proposed offering';
 const [hypothesis,setHypothesis]=useState(`Customers have a recurring problem with ${topic.toLowerCase()} that current alternatives do not solve.`),[segment,setSegment]=useState(''),[target,setTarget]=useState(10),[required,setRequired]=useState(6),[error,setError]=useState('');
 function create(){const parsed=experimentSchema.safeParse({id:crypto.randomUUID(),created:new Date().toISOString(),hypothesis,segment,target,required,completed:0,positive:0,notes:'',baseline:report.overall_score,interpretation:report.interpretation});if(!parsed.success){setError('Add a hypothesis and customer segment. Use whole targets from 1–10,000; required supporting responses cannot exceed the target.');return}if(records.save([...records.items,parsed.data])){setError('');setHypothesis('')}}
 return <section className="report-section" id="validation-lab"><h2>Customer validation lab</h2><p>Turn a report observation into a small customer experiment. Define success before collecting responses. Plans remain fixed after creation so the original criterion stays visible.</p><p className="hint">Records stay in this browser for this report, outside shared links. Other users of this browser profile can read them. Export a backup before clearing browser data.</p>
 <details><summary>Interview guide</summary><ol><li>Tell me about the last time you faced this problem.</li><li>What did you use instead, and what did it cost in time or money?</li><li>How often has this happened in the last month?</li><li>What would make you keep your current alternative?</li><li>What evidence would convince us this hypothesis is wrong?</li></ol><p>Count a response as supporting only when it meets your hypothesis. A small convenience sample does not prove population-level demand.</p></details>
 <label>Experiment hypothesis<textarea rows={2} maxLength={1000} value={hypothesis} onChange={e=>setHypothesis(e.target.value)}/></label><div className="research-form"><label>Customer segment<input maxLength={200} value={segment} onChange={e=>setSegment(e.target.value)} placeholder="Freelancers working near the station"/></label><label>Response target<input type="number" min={1} max={10000} value={target} onChange={e=>setTarget(e.target.valueAsNumber)}/></label><label>Required supporting responses<input type="number" min={1} max={10000} value={required} onChange={e=>setRequired(e.target.valueAsNumber)}/></label></div><div className="report-actions"><button className="primary" disabled={records.items.length>=100} onClick={create}>Create experiment</button><button className="secondary" disabled={!records.items.length} onClick={records.download}>Export experiments</button></div>{error&&<p role="alert">{error}</p>}<p role="status">{records.message}</p>
 {!records.items.length&&<p className="empty">No experiments saved yet.</p>}{records.items.map(item=><Results key={item.id} item={item} save={next=>records.save(records.items.map(v=>v.id===next.id?next:v))}/>)}</section>;
}
