import {useState} from 'react';
import type {Evidence} from '../types/novelty';
type State='missing'|'partial'|'satisfied'|'not applicable';
type Kind='mandatory'|'advisory'|'expectation'|'unknown';
type Criterion={id:string;text:string;kind:Kind;state:State;claimIds:string[];evidenceIds:string[];task:string;note:string;reason:string};
type Saved={guidelineUrl:string;version:string;criteria:Criterion[]};
function read(key:string):Saved{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value?{guidelineUrl:value.guidelineUrl||'',version:value.version||'',criteria:Array.isArray(value.criteria)?value.criteria:[]}:{guidelineUrl:'',version:'',criteria:[]}}catch{return {guidelineUrl:'',version:'',criteria:[]}}}
function exportCsv(saved:Saved){const rows=[['criterion','type','status','claim IDs','evidence IDs','task','mapping note','reason','guideline URL','version'],...saved.criteria.map(item=>[item.text,item.kind,item.state,item.claimIds.join('; '),item.evidenceIds.join('; '),item.task,item.note,item.reason,saved.guidelineUrl,saved.version])];const csv=rows.map(row=>row.map(value=>'"'+value.replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='venue-criteria-map.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function VenueCriteriaMapper({reportId,claims,evidence}:{reportId:string;claims:{id:string;text:string}[];evidence:Evidence[]}){
 const key='novelty-defense-'+reportId+'-venue-criteria';const [saved,setSaved]=useState(()=>read(key));const [text,setText]=useState(()=>read(key).criteria.map(item=>item.text).join('\n'));const [storageError,setStorageError]=useState(false);
 const persist=(next:Saved)=>{setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}};
 const importCriteria=()=>{const next=text.split('\n').map(line=>line.trim()).filter(Boolean).slice(0,100).map(criterion=>saved.criteria.find(item=>item.text===criterion)||({id:crypto.randomUUID(),text:criterion,kind:'unknown' as const,state:'missing' as const,claimIds:[],evidenceIds:[],task:'',note:'',reason:''}));persist({...saved,criteria:next})};
 const update=(id:string,patch:Partial<Criterion>)=>persist({...saved,criteria:saved.criteria.map(item=>item.id===id?{...item,...patch}:item)});
 const counts={satisfied:saved.criteria.filter(item=>item.state==='satisfied'&&((item.claimIds.length+item.evidenceIds.length>0)||item.task.trim()||item.reason.trim())).length,partial:saved.criteria.filter(item=>item.state==='partial').length,missing:saved.criteria.filter(item=>item.state==='missing').length,notApplicable:saved.criteria.filter(item=>item.state==='not applicable').length};
 const changeClaims=(item:Criterion,id:string,checked:boolean)=>update(item.id,{claimIds:checked?[...new Set([...item.claimIds,id])]:item.claimIds.filter(value=>value!==id)});
 const changeEvidence=(item:Criterion,id:string,checked:boolean)=>update(item.id,{evidenceIds:checked?[...new Set([...item.evidenceIds,id])]:item.evidenceIds.filter(value=>value!==id)});
 return <>
  <p>Paste the current venue criteria, one requirement per line, and map each line to project material. Copy the official wording and record the page version or access date.</p>
  <div className="tool-input-grid"><label>Official guidelines URL<input type="url" value={saved.guidelineUrl} onChange={event=>persist({...saved,guidelineUrl:event.target.value})} placeholder="https://venue.example/guidelines"/></label><label>Guideline version or access date<input value={saved.version} onChange={event=>persist({...saved,version:event.target.value})} placeholder="Version, issue, or date checked"/></label></div>
  <label>Criteria, one per line<textarea rows={7} value={text} onChange={event=>setText(event.target.value)} maxLength={15000}/></label><button type="button" className="quiet-button" onClick={importCriteria}>Import criteria and preserve matching mappings</button>
  {saved.criteria.length>0&&<><div className="coverage-strip"><span>Satisfied with a mapping<b>{counts.satisfied}</b></span><span>Partial<b>{counts.partial}</b></span><span>Missing<b>{counts.missing}</b></span><span>Not applicable<b>{counts.notApplicable}</b></span></div><div className="venue-map-list">{saved.criteria.map(item=><article key={item.id}><header><b>{item.text}</b><button type="button" className="quiet-button" onClick={()=>persist({...saved,criteria:saved.criteria.filter(value=>value.id!==item.id)})}>Remove</button></header><div className="tool-input-grid"><label>Requirement type<select value={item.kind} onChange={event=>update(item.id,{kind:event.target.value as Kind})}><option>unknown</option><option>mandatory</option><option>advisory</option><option>expectation</option></select></label><label>Mapping status<select value={item.state} onChange={event=>update(item.id,{state:event.target.value as State})}><option>missing</option><option>partial</option><option>satisfied</option><option>not applicable</option></select></label></div><p>Map to claims:</p><div className="defense-checks">{claims.map(claim=><label key={claim.id}><input type="checkbox" checked={item.claimIds.includes(claim.id)} onChange={event=>changeClaims(item,claim.id,event.target.checked)}/>{claim.text}</label>)}</div><p>Map to evidence:</p><div className="defense-checks">{evidence.map(source=><label key={source.id}><input type="checkbox" checked={item.evidenceIds.includes(source.id)} onChange={event=>changeEvidence(item,source.id,event.target.checked)}/>{source.title}</label>)}</div><label>Experiment, report section, or task<textarea rows={2} value={item.task} onChange={event=>update(item.id,{task:event.target.value})} placeholder="Name the experiment, manuscript section, or action that satisfies the criterion"/></label><label>Mapping note or not-applicable reason<textarea rows={2} value={item.reason} onChange={event=>update(item.id,{reason:event.target.value})} placeholder="Explain the link or why this requirement does not apply"/></label>{item.state==='satisfied'&&!item.claimIds.length&&!item.evidenceIds.length&&!item.task.trim()&&!item.reason.trim()&&<p className="warning-line">A satisfied criterion needs a mapped artifact or a written reason.</p>}</article>)}</div><button type="button" className="quiet-button" onClick={()=>exportCsv(saved)}>Export criteria map CSV</button></>}
  {storageError&&<p className="warning-line" role="alert">Venue criteria map could not be saved in this browser.</p>}
  <small>Venue instructions can change. Confirm current requirements at the official source before submission. A status label is a team assessment, not venue approval.</small>
 </>;
}
