import {parseStoredRecord,writeStoredRecord} from '../../lib/projectRecords';
import {useState} from 'react';
import {useSearchParams,useLocation,useNavigate} from 'react-router-dom';
import type {Evidence,Guidance} from '../../types/novelty';
import {EvidenceDetail} from './EvidenceDetail';

type Decision={state:string;reason:string};
function read<T>(key:string,fallback:T):T{try{const value:unknown=parseStoredRecord(key,'null');if(Array.isArray(fallback))return Array.isArray(value)&&value.every(item=>typeof item==='string')?value as T:fallback;if(!value||typeof value!=='object'||Array.isArray(value))return fallback;return Object.values(value).every(item=>item&&typeof item==='object'&&typeof item.state==='string'&&typeof item.reason==='string')?value as T:fallback;}catch{return fallback;}}
export function EvidenceBrowser({evidence,originalIds,id,comparisons=[]}:{evidence:Evidence[];originalIds:Set<string>;id:string;comparisons?:Guidance['closest_work']}){
  const [params]=useSearchParams();const navigate=useNavigate(),location=useLocation();function setParams(next:URLSearchParams,options:{replace?:boolean}={}){navigate({search:'?'+next.toString(),hash:location.hash},options);}const [screening,setScreening]=useState<Record<string,Decision>>(()=>read(`novelty-tools-${id}-screening`,{}));const [queue,setQueue]=useState<string[]>(()=>read(`novelty-tools-${id}-queue`,[]));const [message,setMessage]=useState('');
  const term=params.get('q')||'',type=params.get('type')||'all',sort=params.get('sort')||'match',state=params.get('screen')||'all',from=params.get('from')||'',to=params.get('to')||'';
  function change(key:string,value:string){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);next.delete('page');setParams(next,{replace:true});}
  const year=(item:Evidence)=>Number((item.publication_date||item.priority_date||'').slice(0,4));
  const filtered=evidence.filter(item=>(type==='all'||item.source_type===type)&&(!term||`${item.title} ${item.summary_text} ${(item.authors||[]).join(' ')}`.toLowerCase().includes(term.toLowerCase()))&&(state==='all'||(state==='queued'?queue.includes(item.id):(screening[item.id]?.state||'unreviewed')===state))&&(!from||year(item)>=Number(from))&&(!to||year(item)<=Number(to))).sort((a,b)=>sort==='year'?(year(b)||0)-(year(a)||0):sort==='title'?a.title.localeCompare(b.title):b.similarity_score-a.similarity_score);
  const pages=Math.max(1,Math.ceil(filtered.length/10));const requested=Number(params.get('page'));const page=Math.max(1,Math.min(pages,Number.isInteger(requested)?requested:1));const selected=evidence.find(item=>item.id===params.get('source'));
  function save<T>(key:string,value:T,update:(value:T)=>void){update(value);try{writeStoredRecord(key,JSON.stringify(value));setMessage('Saved in this browser.');}catch{setMessage('Changes are in memory only. Browser storage is unavailable.');}}
  function decision(item:Evidence,patch:Partial<Decision>){save(`novelty-tools-${id}-screening`,{...screening,[item.id]:{...(screening[item.id]||{state:'unreviewed',reason:''}),...patch}},setScreening);}
  if(selected)return <><button className="quiet-button" onClick={()=>{const next=new URLSearchParams(params);next.delete('source');setParams(next);}}>← Back to filtered sources</button><EvidenceDetail item={selected} original={originalIds.has(selected.id)} comparison={comparisons.find(item=>item.evidence_id===selected.id)}/><label>Screening decision<select value={screening[selected.id]?.state||'unreviewed'} onChange={e=>decision(selected,{state:e.target.value})}>{['unreviewed','include','exclude','maybe'].map(value=><option key={value}>{value}</option>)}</select></label><label>Reason for this decision<textarea value={screening[selected.id]?.reason||''} onChange={e=>decision(selected,{reason:e.target.value})}/></label><button className="quiet-button" onClick={()=>save(`novelty-tools-${id}-queue`,queue.includes(selected.id)?queue.filter(value=>value!==selected.id):[...queue,selected.id],setQueue)}>{queue.includes(selected.id)?'Remove from reading queue':'Add to reading queue'}</button><p role="status">{message}</p></>;
  return <section>{params.get('source')&&<p role="status">That source is not available in this report. Browse the current sources below.</p>}<p>Browse excerpts, then inspect the original source. Added records do not change the saved report scores.</p><div className="evidence-filters"><label>Search sources<input type="search" value={term} onChange={e=>change('q',e.target.value)}/></label><label>Source type<select value={type} onChange={e=>change('type',e.target.value)}><option value="all">All sources</option><option value="scholar">Papers</option><option value="patent">Patents</option><option value="web">Public web</option></select></label><label>Review state<select value={state} onChange={e=>change('screen',e.target.value)}>{['all','unreviewed','include','exclude','maybe','queued'].map(value=><option key={value}>{value}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>change('sort',e.target.value)}><option value="match">Closest text match</option><option value="year">Newest publication</option><option value="title">Title</option></select></label><label>From year<input type="number" min="1800" max="2100" value={from} onChange={e=>change('from',e.target.value)}/></label><label>Through year<input type="number" min="1800" max="2100" value={to} onChange={e=>change('to',e.target.value)}/></label></div><p role="status">{filtered.length} of {evidence.length} sources · page {page} of {pages}</p><div className="source-rows">{filtered.slice((page-1)*10,page*10).map(item=><article key={item.id}><button className="source-title" onClick={()=>{const next=new URLSearchParams(params);next.set('source',item.id);setParams(next);}}>{item.title}</button><p className="hint">{item.source_type==='scholar'?'Paper':item.source_type==='patent'?'Patent':'Public web'} · {item.publication_date||item.priority_date||'Date unknown'} · {item.similarity_score}% match · {screening[item.id]?.state||'Unreviewed'}{queue.includes(item.id)?' · Queued':''}{originalIds.has(item.id)?'':' · Added source'}</p><p className="source-excerpt">{item.summary_text||'No excerpt returned.'}</p></article>)}</div>{!filtered.length&&<p>No sources match these filters. Clear a filter or add sources using Additional retrieval below.</p>}<div className="pagination"><button className="quiet-button" disabled={page<=1} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(page-1));setParams(next);}}>Previous page</button><button className="quiet-button" disabled={page>=pages} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(page+1));setParams(next);}}>Next page</button></div></section>;
}
