import {Link,useLocation} from 'react-router-dom';
import type {NoveltyReport} from '../../types/novelty';
import {reportDestination} from './ReportShell';

export function ReportOverview({report:r}:{report:NoveltyReport}){
  const location=useLocation();const evidence=[...r.papers,...r.patents,...r.web_results].sort((a,b)=>b.similarity_score-a.similarity_score);const coverage=r.research_guidance?.coverage;
  const link=(view:'claims'|'evidence'|'study'|'record')=>({search:reportDestination(location.search,view),hash:location.hash});
  return <>
    <section className="overview-interpretation"><h3>What this search suggests</h3><p className="overview-verdict">{r.interpretation}</p><div className="overview-signals"><p><strong>{r.overlap_score}/100</strong> Search overlap</p><p><strong>{r.confidence_score}/100</strong> Evidence confidence · {r.confidence_label}</p></div><p>{r.summary.disclaimer}</p><Link to={link('record')}>Inspect queries, scores, and limitations</Link></section>
    <section className="overview-section"><h3>Search coverage</h3><dl className="overview-counts"><div><dt>Papers</dt><dd>{r.papers.length}</dd></div><div><dt>Patents</dt><dd>{r.patents.length}</dd></div><div><dt>Public web</dt><dd>{r.web_results.length}</dd></div><div><dt>Full texts inspected</dt><dd>{coverage?.full_texts_inspected??0}</dd></div></dl><p className="hint">These counts describe the retrieved set, not the complete field. Sources you add later do not change the original scores.</p>{r.warnings.length>0&&<p className="warning-line">{r.warnings[0]} {r.warnings.length>1&&<Link to={link('record')}>Read all {r.warnings.length} warnings</Link>}</p>}</section>
    <section className="overview-section"><div className="section-head"><h3>Closest retrieved work</h3><Link to={link('evidence')}>Browse all {evidence.length} sources</Link></div><ol className="closest-list">{evidence.slice(0,3).map(item=><li key={item.id}><Link to={{search:reportDestination(location.search,'evidence')+'&source='+encodeURIComponent(item.id),hash:location.hash}}>{item.title}</Link><small>{item.source_type==='scholar'?'Paper':item.source_type==='patent'?'Patent':'Public web'} · {item.similarity_score}% text match</small></li>)}</ol>{!evidence.length&&<p>No sources were returned. Inspect the queries in Record and broaden the search.</p>}</section>
    <section className="overview-section"><div className="section-head"><h3>Claims needing attention</h3><Link to={link('claims')}>Review all claims</Link></div>{r.summary.least_covered_claims.length?<ul>{r.summary.least_covered_claims.slice(0,3).map(claim=><li key={claim.id}>{claim.text}<small>{claim.coverage_label} coverage · {claim.coverage_score}%</small></li>)}</ul>:<p>{r.claims.length?'No claim is below the report’s coverage threshold. Review source relevance before treating matches as support.':'Add key claims in Claims to make the comparison more specific.'}</p>}<p className="hint">Low coverage is a reason to search further; it does not establish novelty.</p></section>
    <section className="overview-section"><h3>Three useful next steps</h3><ol className="next-actions"><li><Link to={link('evidence')}>Read the closest original source</Link><p>Check the methods and conditions behind the excerpt.</p></li><li><Link to={link('claims')}>Narrow the claim you can defend</Link><p>Separate shared components from the difference you propose.</p></li><li><Link to={link('study')}>Plan a fair comparison</Link><p>Choose a baseline and a measurement that tests that difference.</p></li></ol></section>
  </>;
}
