import {lazy,Suspense,useState} from 'react';
import {Link,useSearchParams,useLocation} from 'react-router-dom';
import type {NoveltyReport} from '../../types/novelty';
import {NoveltyWorkspace} from '../NoveltyWorkspace';
import {ResearchWorkspaceSync} from '../ResearchWorkspaceSync';
import {ResearchProjectTransfer} from '../ResearchProjectTransfer';
import {ResearchRetrieval} from '../ResearchRetrieval';
import {reportView,researchTools} from '../../lib/researchToolRegistry';
import {ReportShell,reportDestination} from './ReportShell';
import {ReportOverview} from './ReportOverview';
import {EvidenceBrowser} from './EvidenceBrowser';
import {CopyLink,publicReportUrl} from './CopyLink';
import {ToolFinder} from './ToolFinder';
const ToolHost=lazy(()=>import('./ToolHost').then(module=>({default:module.ToolHost})));

export function ResearchReport({report:r,expanded,id,homePath,reportBase,revision}:{report:NoveltyReport;expanded:NoveltyReport;id:string;homePath:string;reportBase:string;revision:number}){
  const [params]=useSearchParams();const location=useLocation();const view=reportView(params.get('view'));const tool=researchTools.find(item=>item.id===params.get('tool')&&item.view===view);const [finder,setFinder]=useState(false);
  const originalIds=new Set([...r.papers,...r.patents,...r.web_results].map(item=>item.id));
  return <div className="wrap report-page"><Link to={homePath} className="back-link">← New research</Link>{r.sample_mode&&<div className="sample-banner"><strong>Illustrative sample</strong><span>The evidence is fictional and demonstrates the workflow. No provider search was run.</span></div>}<header className="report-title"><div><p className="kicker">Research overlap report · {r.sample_mode?'prepared sample':r.is_public?'public':'unlisted'}</p><h1>{r.input.title}</h1><p>{r.input.field||'Research field not provided'}{r.created_at?` · ${new Date(r.created_at).toLocaleDateString()}`:''}</p></div><div className="report-header-actions"><CopyLink value={publicReportUrl(location.pathname?window.location.href:window.location.href)}/><button className="quiet-button" aria-expanded={finder} onClick={()=>setFinder(!finder)}>{finder?'Close tool finder':'Find a tool'}</button></div></header><ReportShell>{finder&&<ToolFinder view={view}/>}{tool?<><Link className="back-link" to={{search:reportDestination(location.search,view),hash:location.hash}}>← Back to {view}</Link><Suspense fallback={<p role="status">Loading {tool.title}…</p>}><ToolHost key={id+revision+tool.id} tool={tool} report={expanded} id={id}/></Suspense></>:<>
  {view==='overview'&&<ReportOverview report={r}/>}
  {view==='evidence'&&<><EvidenceBrowser key={id+revision} id={id} evidence={[...expanded.papers,...expanded.patents,...expanded.web_results]} originalIds={originalIds}/>{!params.get('source')&&<><details className="support-section"><summary>Additional retrieval</summary><ResearchRetrieval key={id+revision} id={id} idea={r.input.title}/></details><details className="support-section"><summary>Publication timeline and people</summary><h3>Prior work timeline</h3><ul>{r.timeline.map((item,index)=><li key={index}>{item.year} · {item.title}</li>)}</ul>{[['Paper authors',r.author_summary],['Inventors',r.inventor_summary],['Assignees',r.assignee_summary]].map(([label,items])=><div key={String(label)}><h3>{String(label)}</h3><ul>{(items as {name:string;count:number}[]||[]).map(item=><li key={item.name}>{item.name} · {item.count} retrieved records</li>)}</ul></div>)}</details></> }</>}
  {view==='claims'&&<section><h3>Claim evidence map</h3>{r.claims.length?r.claims.map(claim=><details className="claim-row" key={claim.id}><summary>{claim.text}<small>{claim.matches.length} matching records · {claim.coverage_label} coverage · {claim.coverage_score}%</small></summary><p>Matched terms: {claim.matched_terms.join(', ')||'None identified'}</p>{claim.matches.map(match=><article key={match.evidence_id}><Link to={{search:reportDestination(location.search,'evidence')+'&source='+encodeURIComponent(match.evidence_id),hash:location.hash}}>{match.title}</Link><p>{match.excerpt||'No excerpt available.'}</p><small>{match.similarity_score}% text match · {match.source_type}</small></article>)}{!claim.matches.length&&<p>No matching evidence was returned. Broaden the search before concluding there is a gap.</p>}</details>):<p>No key claims were supplied. Compare a revised version below.</p>}</section>}
  {view==='study'&&<p>Start with a fair baseline, align each claim with a measurement, then define a bounded study. These tools record your judgments; they do not replace expert review.</p>}
  {view==='review'&&<><p>Assign verification tasks, record feedback, and decide whether the evidence supports continuing. Reviewer names are self-entered, not verified identities.</p>{r.sample_mode&&<p className="hint">The sample supports local planning. Shared supervisor feedback requires a saved, unlisted report.</p>}<ResearchWorkspaceSync key={id+revision} report={r} id={id}/></>}
  {view==='record'&&<><section><h3>Visibility and retention</h3><p>{r.sample_mode?'This prepared sample contains fictional evidence.':r.is_public?'This report is publicly listed. Anyone can view the submitted idea and evidence.':`Anyone with this unlisted link can read the report. ${r.saved?'It expires after seven days.':'It expires after one hour.'}`}</p><p>Local records and drafts are separate from the saved report. Export records before switching browsers; shared records require an explicit publish action in Review.</p></section><ResearchProjectTransfer key={id+revision} report={r} id={id}/><section className="report-section"><h3>Searches and scoring</h3><p>Search-based novelty signal: {r.novelty_signal}/100. This is 100 minus overlap, not an independent novelty assessment.</p><h4>Exact searches used</h4><ul className="query-list">{r.queries.map((query,index)=><li key={index}><span>{query.engine}</span><code>{query.query}</code></li>)}</ul><h4>Overlap formula</h4><code>0.50 × top match + 0.30 × mean top five + 0.20 × high-match breadth</code><h4>Per-record similarity</h4><code>0.60 × TF-IDF + 0.25 × claim coverage + 0.15 × phrase coverage</code><p>Searches are incomplete. Text similarity is not a legal or scientific judgment. Weak matches can reflect missing sources or query coverage.</p>{[...r.warnings,...r.ai_analysis.warnings].map((warning,index)=><p className="warning-line" key={index}>{warning}</p>)}<p>Methodology {r.methodology_version} · {r.credential_mode} mode</p></section></>}
  {view==='claims'&&(r.ai_analysis.executive_summary||r.ai_analysis.claim_explanations?.length)&&<details className="support-section"><summary>Optional evidence explanations</summary><p>These explanations do not assign scores.</p><p>{r.ai_analysis.executive_summary}</p>{r.ai_analysis.claim_explanations?.map((item,index)=><article key={index}><h3>{r.claims.find(claim=>claim.id===item.claim_id)?.text||'Research claim'} · {item.assessment}</h3><p>{item.explanation}</p><p>{item.limitations.join(' · ')}</p></article>)}{r.ai_analysis.areas_needing_deeper_search?.map((item,index)=><article key={index}><p>{item.reason}</p>{item.suggested_queries.map(query=><code key={query}>{query}</code>)}</article>)}</details>}
  {view!=='overview'&&<ToolFinder view={view}/>}
  </>}
  <div hidden={Boolean(tool)}><NoveltyWorkspace report={r} id={id} reportBase={reportBase} view={tool?'none':view}/></div>
  </ReportShell></div>;
}
