import {useState} from 'react';
import {ConnectionDiagram} from './ConnectionDiagram';
import {useLocalRecords} from '../../lib/useLocalRecords';
import {evidenceNodes,noteSchema} from '../../lib/strategy';
import type {Report} from '../../types/analysis';
export function EvidenceGraph({report:r}:{report:Report}){
 const records=useLocalRecords(`venture-graph-v1:${r.id}`,noteSchema),sources=evidenceNodes(r);const [kind,setKind]=useState<'Finding'|'Assumption'|'Decision'>('Finding'),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>([]),[focus,setFocus]=useState('');
 const visible=focus?records.items.filter(n=>n.id===focus||n.sources.includes(focus)):records.items;const relevant=new Set(visible.flatMap(n=>n.sources));const sourceRows=focus?sources.filter(s=>s.id===focus||relevant.has(s.id)):sources;
 return <><p>Connect findings, assumptions and decisions to saved evidence. Links record your reasoning; they do not verify the claim.</p><ConnectionDiagram sources={sources} notes={records.items} focus={focus} onFocus={setFocus}/><div className="connection-map"><section><h3>Evidence</h3>{sourceRows.map(s=><button className={focus===s.id?'selected':''} key={s.id} onClick={()=>setFocus(focus===s.id?'':s.id)}>{s.title}<small>{s.engine}</small></button>)}{!sourceRows.length&&<p>No connected source records.</p>}</section><section><h3>Your reasoning</h3>{visible.map(n=><article key={n.id}><button className="text-button" onClick={()=>setFocus(focus===n.id?'':n.id)}>{n.kind}: {n.text}</button><ul>{n.sources.map(id=>{const s=sources.find(s=>s.id===id),note=records.items.find(s=>s.id===id);return <li key={id}>{s?.url?<a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>:s?.title||note?.text||'Source unavailable'}</li>})}</ul><button className="text-button" onClick={()=>records.save(records.items.filter(v=>v.id!==n.id).map(v=>({...v,sources:v.sources.filter(id=>id!==n.id)})))}>Remove note</button></article>)}{!visible.length&&<p>Add a note and connect its sources below.</p>}</section></div>{focus&&<button className="secondary" onClick={()=>setFocus('')}>Show all connections</button>}<form onSubmit={e=>{e.preventDefault();if(records.save([...records.items,{id:crypto.randomUUID(),kind,text,sources:selected}])){setText('');setSelected([])}}}><label>Reasoning type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{['Finding','Assumption','Decision'].map(v=><option key={v}>{v}</option>)}</select></label><label>Your reasoning<textarea required minLength={3} maxLength={600} value={text} onChange={e=>setText(e.target.value)}/></label><fieldset><legend>Connect evidence or earlier reasoning (up to 20)</legend>{[...sources.map(s=>({id:s.id,title:s.title})),...records.items.map(n=>({id:n.id,title:n.kind+': '+n.text}))].map(s=><label className="checkbox" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selected.length>=20} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.title}</label>)}</fieldset><button className="primary">Save connection</button></form><p role="status">{records.message}</p><button className="secondary" onClick={records.download}>Export connections</button></>;
}
