export interface AnalysisInput {business_category:string;city:string;country:string;keywords:string[];known_competitors:string[];refresh?:boolean}
export interface Competitor {data_id:string|null;name:string;address:string|null;rating:number|null;review_count:number;latitude:number|null;longitude:number|null;website:string|null;price:string|null;source_url:string|null;rank:number}
export interface Review {data_id?:string|null;competitor:string;rating:number;text:string;source_url:string|null;published_at:string|null}
export interface Topic {topic:string;mentions:number;competitor_count:number;repeated:boolean;competitors?:{data_id:string|null;competitor:string}[];excerpts:Review[]}
export interface News {title:string;source:string;snippet:string;source_url:string|null;published_at:string|null;sentiment:string;matched_keywords:string[];weight:number}
export interface Ad {advertiser:string;creative_id:string;source_url:string|null;first_shown:string|null;last_shown:string|null;format:string;registration_country:string|null;destination_url:string|null;platforms:string[]}
export interface Section {status:string;count:number;message?:string}
export interface Evidence {id:string;title:string;engine:string;evidence_type:string;snippet:string|null;source_url:string|null;published_at:string|null;source_name:string}
export type ScoreKey = 'demand'|'competition_gap'|'unmet_need'|'market_momentum'|'advertising_gap';
export interface Citation {text:string;href:string}
export interface Report {id:string;status:'complete';input:AnalysisInput;overall_score:number;confidence_score:number;confidence_label:string;interpretation:string;component_scores:Record<ScoreKey,number>;recommendation:{headline:string;strengths:Citation[];risks:Citation[];next_checks:Citation[]};competitors:Competitor[];trend_series:{date:string;values:Record<string,number>}[];review_topics:Topic[];news:News[];advertising:Ad[];evidence:Evidence[];warnings:string[];sections:Record<string,Section>;data_mode:'live'|'fixture';methodology_version:string;methodology:{weights:Record<ScoreKey,number>;components:Record<ScoreKey,{formula:string;[key:string]:unknown}>;confidence_points:Record<string,number>;confidence_rule:string;reference_date:string};created_at:string}
export interface Job {id:string;status:'queued'|'running'|'failed';stage:string;progress:number;warnings:string[];sections:Record<string,Section>;error_message?:string}
export interface Summary {id:string;business_category:string;city:string;country:string;overall_score:number;confidence_score:number;interpretation:string;created_at:string;data_mode:string}
export interface AnalysisInput {options?:import('../lib/marketTools').SearchOptions}
export interface Competitor {operating_hours?:Record<string,string>}
export interface SearchUsage {mode:string;total_requests:number;total_provider_attempts:number;logical_requests:Record<string,number>;provider_attempts:Record<string,number>;billing_note:string}
export interface Reputation {data_id:string|null;competitor:string;status:string;recent_count:number;older_count:number;ignored_count:number;recent_average:number|null;older_average:number|null;delta:number|null;direction:string;recent:Review[];older:Review[];reference_date:string}
export interface RelevanceAudit {source_report_id:string;generated_at:string;reason:string;excluded_competitors:{rank:number;name:string}[];excluded_news:{title:string;source_url:string|null}[];original_score:number}
export interface Report {reputation?:Reputation[];search_usage?:SearchUsage;relevance_audit?:RelevanceAudit}
export interface Job {search_usage?:SearchUsage}
