export type Evidence = {id:string;source_type:'scholar'|'patent'|'web';title:string;summary_text:string;source_url?:string|null;pdf_url?:string|null;publication_date?:string;priority_date?:string;citation_count?:number|null;versions?:number|null;similarity_score:number;matched_claims?:{claim_id:string;similarity_score:number}[];authors?:string[];inventors?:string[];assignees?:string[];patent_id?:string;legal_status?:string;details?:Record<string,unknown>;family_members?:{title:string;patent_id?:string;source_url?:string;priority_date?:string}[];evidence_strength?:number};
export type Claim = {id:string;text:string;coverage_score:number;coverage_label:string;matched_terms:string[];matches:{evidence_id:string;source_type:string;title:string;url?:string|null;similarity_score:number;excerpt:string}[]};
export type NoveltyReport = {id:string;status:'complete';input:{title:string;abstract:string;field?:string;keywords:string[];claims:string[]};queries:{engine:string;query:string;timestamp:string}[];overlap_score:number;novelty_signal:number;confidence_score:number;confidence_label:string;interpretation:string;credential_mode:string;sample_mode?:boolean;is_public?:boolean;saved?:boolean;research_guidance?:Guidance;ai_analysis:{status:string;model?:string|null;prompt_version?:string;call_count?:number;executive_summary:string;claim_explanations?:{claim_id:string;assessment:string;explanation:string;evidence_ids:string[];limitations:string[]}[];areas_needing_deeper_search?:{claim_id:string;reason:string;suggested_queries:string[]}[];report_limitations?:string[];warnings:string[]};summary:{strongest_overlaps:Evidence[];least_covered_claims:Claim[];disclaimer:string};claims:Claim[];papers:Evidence[];patents:Evidence[];web_results:Evidence[];timeline:{year:number;source_type:string;title:string;url?:string}[];assignee_summary?:{name:string;count:number}[];inventor_summary?:{name:string;count:number}[];author_summary?:{name:string;count:number}[];warnings:string[];methodology_version:string;created_at:string};
export type Job = {id:string;status:'queued'|'running'|'failed';stage:string;progress:number;error_message?:string|null};
export type Guidance = {
 contributions:{dimension:string;proposal_terms:string[];evidence_matches:{evidence_id:string;title:string;source_url?:string|null;shared_terms:string[];excerpt:string}[];assessment:string}[];
 closest_work:{evidence_id:string;title:string;source_url?:string|null;source_type:string;similarity_score:number;shared_terms:string[];proposal_terms_not_in_excerpt:string[];excerpt:string;limitation:string}[];
 coverage:{queries_by_engine:Record<string,number>;records_by_source:Record<string,number>;earliest_returned_year:number|null;latest_returned_year:number|null;full_texts_inspected:number;source_warnings:string[];next_checks:string[]};
 gap_hypotheses:{claim_id:string;hypothesis:string;basis:string;follow_up_query:string;status:string}[];
 experiments:{claim_id:string;question:string;baseline_evidence_id:string|null;baseline_title:string;suggested_checks:string[];limitation:string}[];
};
export type RevisionPreview={baseline_id:string;baseline_overlap:number;preview_overlap:number;delta:number;claim_comparison:{claim:string;previous_coverage:number|null;preview_coverage:number}[];guidance:Guidance;limitation:string};
export type DocumentReview={page_count:number;pages_checked:number;claims:{claim_id:string;claim:string;passages:{page:number;text:string;similarity:number}[]}[];limitation:string};
export type ReviewComment={id:string;author:string;claim_id:string|null;kind:string;text:string;source_url?:string|null;created_at:string};
export type Workspace={comments:ReviewComment[];watched:boolean;latest_report_id:string|null;alerts:{kind:string;title:string;source_url?:string|null;report_id:string}[]};
