import {offerQuotaKeys,personalKeysActive,personalGroqActive} from '../api/providerKeys';
import {useResearchDraft} from '../lib/researchDraft';
import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link,useNavigate} from 'react-router-dom';
import {noveltyApi,NoveltyApiError} from '../api/novelty';

const demo={title:'Privacy-preserving crop disease detection on low-power phones',field:'Computer science / agriculture',keywords:'crop disease detection, on-device learning, privacy, low-power smartphone, federated learning',abstract:'A mobile system that detects crop disease from leaf images while keeping farm images on the device. The system uses a compact vision model, optional federated updates, and confidence-based referral when prediction certainty is low.',claims:'Crop disease inference runs fully on low-power mobile hardware.\nTraining improvements can be shared without uploading raw farm images.\nLow-confidence predictions are routed for expert review.',earliest_year:'',related_work:''};
export function HomePage({reportBase='/reports'}:{reportBase?:string}){
 const [form,setForm]=useResearchDraft('new-idea','form',()=>Object.fromEntries(Object.keys(demo).map(key=>[key,''])) as typeof demo),[error,setError]=useState(''),[busy,setBusy]=useState(false),[makePublic,setMakePublic]=useState(false),[saveReport,setSaveReport]=useState(true),[useGroq,setUseGroq]=useState(false),[replaceExample,setReplaceExample]=useState(false),[draftMessage,setDraftMessage]=useState('');const navigate=useNavigate();const nav=(path:string)=>navigate(reportBase+path.replace(/^\/reports/,''));
 const [personal,setPersonal]=useState(personalKeysActive),[personalAi,setPersonalAi]=useState(personalGroqActive);
 useEffect(()=>{const changed=()=>{setPersonal(personalKeysActive());setPersonalAi(personalGroqActive());setUseGroq(personalGroqActive());};window.addEventListener('provider-keys-changed',changed);return()=>window.removeEventListener('provider-keys-changed',changed);},[]);
 const status=useQuery({queryKey:['demo-status'],queryFn:noveltyApi.status,refetchInterval:30000});
 useEffect(()=>{const update=(event:Event)=>setDraftMessage((event as CustomEvent<string>).detail);window.addEventListener('research-draft-status',update);return()=>window.removeEventListener('research-draft-status',update);},[]);
 useEffect(()=>{if(error)document.getElementById('idea-error')?.focus();},[error]);
 useEffect(()=>{if(status.data?.quota_exhausted)offerQuotaKeys();},[status.data?.quota_exhausted]);
 useEffect(()=>{if(!personal&&status.data?.groq_mode==='available')setUseGroq(true)},[status.data?.groq_mode,personal]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const keywords=form.keywords.split(',').map(x=>x.trim()).filter(Boolean),claims=form.claims.split('\n').map(x=>x.trim()).filter(Boolean),known_related_work=form.related_work.split('\n').map(x=>x.trim()).filter(Boolean),earliest_year=form.earliest_year?Number(form.earliest_year):null;if(keywords.length<3||keywords.length>10||keywords.some(x=>x.length<3||x.length>100)){setError('Enter 3–10 keywords, each 3–100 characters.');return}if(claims.length>3||claims.some(x=>x.length<15||x.length>400)){setError('Enter up to three claims, each 15–400 characters.');return}if(known_related_work.length>10){setError('Enter up to ten known related works.');return}if(earliest_year!=null&&(!Number.isInteger(earliest_year)||earliest_year<1800||earliest_year>2100)){setError('Enter a year from 1800 to 2100.');return}setBusy(true);try{const payload={title:form.title,abstract:form.abstract,field:form.field};const r=await noveltyApi.create({...payload,keywords,claims,known_related_work,earliest_year,is_public:makePublic,save_report:saveReport,use_groq:useGroq});nav(`/reports/${r.id}${r.owner_token?'#owner='+encodeURIComponent(r.owner_token):''}`)}catch(e){setError(e instanceof NoveltyApiError?e.message:'Could not start this search.')}finally{setBusy(false)}}
 return <div className="wrap home">
  <section className="intro"><p className="kicker">Evidence before commitment</p><h1>Describe the idea you want to investigate.</h1><p className="lede">Search academic work, patents and public implementations together. Trace every overlap to its source, and see which claims need a deeper literature review.</p><div className="disclaimer-inline">Search assistance only · No legal or scientific novelty determination</div></section>
  <div className="home-grid"><form className="idea-form" aria-describedby={error?'idea-error':undefined} onSubmit={submit}>
   {!personal&&status.data?.hosted_mode!=='available'&&<div className="capacity" role="status"><strong>{status.data?.hosted_mode==='at_capacity'?'Shared search allowance or server capacity is unavailable':'Hosted search is not configured on this server.'}</strong><span>Use your own API keys, explore the prepared sample, or wait for hosted capacity.</span></div>}
   <div className="form-head"><div><h2>Describe the research</h2><p>Paste an abstract and the phrases you plan to investigate.</p></div><button type="button" className="quiet-button" onClick={()=>{if(Object.values(form).some(value=>value.trim()))setReplaceExample(true);else setForm(demo)}}>Load example</button></div>
   {replaceExample&&<div className="warning-line"><p>Replace your current draft with the example?</p><button type="button" className="quiet-button" onClick={()=>{setForm(demo);setReplaceExample(false);}}>Replace draft</button><button type="button" className="quiet-button" onClick={()=>setReplaceExample(false)}>Keep my draft</button></div>}
   <p className="hint">Your idea draft is saved in this browser. Provider consent and publishing choices are not saved.</p><button type="button" className="quiet-button" onClick={()=>{setForm(Object.fromEntries(Object.keys(demo).map(key=>[key,''])) as typeof demo);setDraftMessage('Idea draft cleared.');}}>Clear idea draft</button><p role="status">{draftMessage}</p>
   <label>Working title<input required minLength={5} maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
   <label>Abstract<textarea required minLength={50} maxLength={2000} rows={6} value={form.abstract} onChange={e=>setForm({...form,abstract:e.target.value})}/><span className="hint">50–2,000 characters</span></label>
<label>Keywords<input required maxLength={1100} value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})}/><span className="hint">3–10 phrases, separated by commas</span></label>
<details className="form-options"><summary>Optional claim and search details</summary><label>Field or domain<input maxLength={160} value={form.field} onChange={e=>setForm({...form,field:e.target.value})} placeholder="e.g. computational biology"/></label>   <label>Key claims<textarea rows={4} maxLength={1200} value={form.claims} onChange={e=>setForm({...form,claims:e.target.value})} placeholder="One claim per line"/><span className="hint">Optional · up to three claims, one per line</span></label>
   <div className="two-col"><label>Search from year <span className="muted">(optional)</span><input type="number" min={1800} max={2100} value={form.earliest_year} onChange={e=>setForm({...form,earliest_year:e.target.value})} placeholder="e.g. 2018"/></label><label>Known related work <span className="muted">(optional)</span><textarea rows={2} maxLength={1000} value={form.related_work} onChange={e=>setForm({...form,related_work:e.target.value})} placeholder="One title, author or publication per line"/></label></div>
</details>
   <label className="consent"><input type="checkbox" disabled={personal?!personalAi:status.data?.groq_mode!=='available'} checked={useGroq} onChange={e=>setUseGroq(e.target.checked)}/><span>Use Groq to extract candidate claims, expand queries and explain retrieved evidence{(personal?!personalAi:status.data?.groq_mode!=='available')?' (add a Groq key to enable)':''}.</span></label>
   <label className="consent"><input type="checkbox" required/><span>I understand the idea text is sent to the configured search provider and, when enabled, Groq for claim/query structuring and evidence explanation.</span></label>
   <label className="consent"><input type="checkbox" checked={saveReport} onChange={e=>{setSaveReport(e.target.checked);if(!e.target.checked)setMakePublic(false)}}/><span>Keep the report for up to 12 days so you can reopen its link. If unchecked, the link expires after one hour.</span></label>
   <label className="consent publish-choice"><input type="checkbox" checked={makePublic} disabled={!saveReport} onChange={e=>setMakePublic(e.target.checked)}/><span>List this report publicly. Anyone can see the submitted idea and evidence. Leave unchecked for an unlisted report.</span></label>
   {error&&<p id="idea-error" tabIndex={-1} role="alert" className="error">{error}</p>}
   <div className="submit-row"><button className="primary-button" type="submit" disabled={busy}>{busy?'Starting search…':'Search papers and patents'}</button><span>No sign-in required</span></div>

  </form>
  <aside className="side-note"><div className="side-top"><span className="signal-icon" aria-hidden="true"><i/><i/><i/></span><div><h2>One idea.<br/>Three evidence streams.</h2><p>Scores stay tied to retrieved text.</p></div></div>
    <ul className="source-rail"><li><b>Scholar</b><span>Related papers and citations</span></li><li><b>Patents</b><span>Claims, dates and patent families</span></li><li><b>Public web</b><span>Implementations and products</span></li></ul>
    <Link className="sample-link" to={reportBase+'/sample'}><span><strong>Open the prepared sample</strong><small>Illustrative report · no API calls</small></span><span aria-hidden="true">↗</span></Link>
    <p className="privacy-note">Reports use unlisted links by default. Avoid pasting unpublished confidential work if it should not be shared with search providers.</p>
  </aside></div>
  <section className="how"><div><span className="step-no">01</span><h3>Search what exists</h3><p>Two query variants look across academic and patent records.</p></div><div><span className="step-no">02</span><h3>Compare each claim</h3><p>Text similarity and phrase coverage connect claims to evidence.</p></div><div><span className="step-no">03</span><h3>Choose what to read</h3><p>Use the report to focus a deeper literature or patent review.</p></div></section>
 </div>
}
