import {useState} from 'react';
import {Link} from 'react-router-dom';

const terms=(text:string)=>new Set((text.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>2));
function similarity(a:string,b:string){const aa=terms(a),bb=terms(b);if(!aa.size||!bb.size)return 0;return Math.round(100*[...aa].filter(x=>bb.has(x)).length/new Set([...aa,...bb]).size)}

export function PrivateResearchPage(){
 const [idea,setIdea]=useState(''),[notes,setNotes]=useState(''),[title,setTitle]=useState(''),[includeFile,setIncludeFile]=useState(''),[result,setResult]=useState<{title:string;score:number;excerpt:string}[]|null>(null),[saveLocal,setSaveLocal]=useState(false);
 function chooseFile(file?:File){if(!file)return;if(file.size>1_000_000){setTitle('Choose a text file under 1 MB.');return}void file.text().then(text=>{setNotes(old=>[old,text].filter(Boolean).join('\n\n'));setIncludeFile(file.name);setTitle('')}).catch(()=>setTitle('This text file could not be read.'))}
 function compare(){if(!idea.trim()||!notes.trim())return;const parts=notes.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).slice(0,100);const ranked=parts.map((text,index)=>({title:text.split('\n')[0].slice(0,160)||`Note ${index+1}`,score:similarity(idea,text),excerpt:text.slice(0,800)})).sort((a,b)=>b.score-a.score);setResult(ranked);if(saveLocal)localStorage.setItem('novelty-private-last',JSON.stringify({title:idea,text:notes}))}
 function exportResult(){const text=`PRIVATE LOCAL REVIEW\n\nIdea:\n${idea}\n\n${(result||[]).map((item,i)=>`${i+1}. ${item.title} (${item.score}% token overlap)\n${item.excerpt}`).join('\n\n')}\n\nThis is a local lexical comparison only. No external search was run.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),link=document.createElement('a');link.href=url;link.download='private-local-review.txt';link.click();URL.revokeObjectURL(url)}
 return <div className="wrap private-page"><Link to="/research-scope" className="back-link">← ResearchScope</Link><p className="kicker">Local only · stays in this browser tab</p><h1>Private research workspace</h1><p>This page makes no API calls. Text is compared in memory in your browser. Upload only plain text, Markdown, BibTeX, or RIS files; PDFs and binary documents are not parsed here.</p><div className="private-form">{localStorage.getItem('novelty-private-last')&&<button className="quiet-button" onClick={()=>{try{const saved=JSON.parse(localStorage.getItem('novelty-private-last')||'{}');setIdea(saved.title||'');setNotes(saved.text||'')}catch{setTitle('Saved local note could not be read.')}}}>Load saved local input</button>}<label>Research idea<textarea rows={6} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Paste an unpublished idea or research question"/></label><label>Private notes and reference text<textarea rows={10} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Paste notes or abstracts you are allowed to use locally"/></label><label>Read a local text file<input type="file" accept=".txt,.md,.bib,.ris,text/plain" onChange={e=>chooseFile(e.target.files?.[0])}/></label>{includeFile&&<small>Loaded locally: {includeFile}</small>}{title&&<p role="alert" className="error">{title}</p>}<label className="consent"><input type="checkbox" checked={saveLocal} onChange={e=>setSaveLocal(e.target.checked)}/><span>Save the last input in browser storage on this device.</span></label><button className="primary-button" disabled={!idea.trim()||!notes.trim()} onClick={compare}>Compare locally</button></div>{result&&<section className="report-section"><h2>Local text matches</h2><p>Token overlap ranks text blocks; it does not search scholarly sources or establish novelty.</p>{result.map((item,i)=><article className="quality-card" key={i}><b>{item.score}% · {item.title}</b><p>{item.excerpt}</p></article>)}<button className="quiet-button" onClick={exportResult}>Download local report</button></section>}</div>
}
