import {lazy,Suspense,useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {noveltyApi} from '../api/novelty';
import type {Evidence,Job,NoveltyReport} from '../types/novelty';
import {NoveltyWorkspace} from '../components/NoveltyWorkspace';
import {ResearchToolkit} from '../components/ResearchToolkit';
import {ResearchWorkspaceSync} from '../components/ResearchWorkspaceSync';
const ResearchDefenseLab=lazy(()=>import('../components/ResearchDefenseLab').then(module=>({default:module.ResearchDefenseLab})));
const ResearchIntegrityLab=lazy(()=>import('../components/ResearchIntegrityLab').then(module=>({default:module.ResearchIntegrityLab})));

function isJob(x:NoveltyReport|Job):x is Job{return x.status!=='complete'}
function EvidenceCard({item}: {item:Evidence}){return <article className="evidence-card"><div className="evidence-top"><span className={'source-tag '+item.source_type}>{item.source_type==='scholar'?'Paper':item.source_type==='patent'?'Patent':'Web evidence'}</span><span className="similarity">{item.similarity_score}% match</span></div><h3>{item.source_url?<a href={item.source_url} target="_blank" rel="noreferrer">{item.title}</a>:item.title}</h3><p>{item.summary_text||'No abstract or snippet was returned by this source.'}</p><div className="evidence-meta">{item.authors?.length?`Authors: ${item.authors.join(', ')}`:''}{item.inventors?.length?`Inventors: ${item.inventors.join(', ')}`:''}{item.assignees?.length?`Assignee: ${item.assignees.join(', ')}`:''}{item.patent_id?`Publication number: ${item.patent_id}`:''}{item.legal_status?`Status: ${item.legal_status}`:''}{item.publication_date?`Published: ${item.publication_date}`:''}{item.priority_date?`Priority: ${item.priority_date}`:''}{item.citation_count!=null?`Cited by ${item.citation_count}`:''}{item.versions!=null?`${item.versions} versions`:''}</div>{item.pdf_url&&<p className="evidence-links"><a href={item.pdf_url} target="_blank" rel="noreferrer">Open PDF</a></p>}
 {item.family_members&&item.family_members.length>0&&<details className="patent-details"><summary>Patent family · {item.family_members.length} records</summary><ul>{item.family_members.map((m,i)=><li key={i}>{m.source_url?<a href={m.source_url} target="_blank" rel="noreferrer">{m.title}</a>:m.title}{m.priority_date?` · priority ${m.priority_date}`:''}</li>)}</ul></details>}
 {item.details&&Object.keys(item.details).length>0&&<details className="patent-details"><summary>Patent details</summary><dl>{Object.entries(item.details).filter(([,v])=>v&&(!Array.isArray(v)||v.length)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{typeof v==='string'?v:Array.isArray(v)?v.map(String).join('; '):JSON.stringify(v)}</dd></div>)}</dl></details>}</article>}

export function ReportPage({homePath='/',reportBase='/reports'}:{homePath?:string;reportBase?:string}){const {id=''}=useParams();const sample=id==='sample';const query=useQuery({queryKey:['novelty-report',id],queryFn:()=>sample?noveltyApi.sample():noveltyApi.report(id),refetchInterval:q=>!q.state.data||isJob(q.state.data as NoveltyReport|Job)?1800:false});
 const [recordRevision,setRecordRevision]=useState(0);
 useEffect(()=>{const update=()=>setRecordRevision(value=>value+1);window.addEventListener('research-workspace-applied',update);return()=>window.removeEventListener('research-workspace-applied',update);},[]);
 if(query.isPending)return <div className="wrap status-page"><p className="kicker">Opening evidence report</p><p role="status">Loading…</p></div>;
 if(query.isError)return <div className="wrap status-page"><p className="kicker">Report unavailable</p><h1>We couldn’t open this report.</h1><p>{query.error instanceof Error?query.error.message:'The report may have expired or its link may be incomplete.'}</p><Link className="primary-button inline-button" to={homePath}>Start a new search</Link></div>;
 const result=query.data as NoveltyReport|Job;
 if(isJob(result)){if(result.status==='failed')return <div className="wrap status-page"><p className="kicker">Search stopped</p><h1>The report could not be completed.</h1><p>{result.error_message}</p><Link to={reportBase+'/sample'}>Open the prepared sample</Link></div>;return <div className="wrap progress-page"><Link to={homePath} className="back-link">← New search</Link><p className="kicker">Building your report</p><h1>Searching the research landscape</h1><p>Retrieved results will be compared against each claim. Source failures remain visible in the completed report.</p><div className="progress-track"><span style={{width:`${result.progress}%`}}/></div><div className="progress-label"><strong>{result.stage.replaceAll('_',' ')}</strong><span>{result.progress}%</span></div><p className="hint">This page updates automatically while the search runs.</p></div>}
 const r=result;
 return <div className="wrap report-page">
  <Link to={homePath} className="back-link">← New search</Link>
  {r.sample_mode&&<div className="sample-banner"><strong>Illustrative sample</strong><span>The evidence below is fictional and exists only to demonstrate the report. No provider search was run.</span></div>}
  <header className="report-title"><div><p className="kicker">Research overlap report {r.sample_mode?'· prepared sample':r.is_public?'· public report':'· unlisted report'}</p><h1>{r.input.title}</h1><p>{r.input.field||'Research field not provided'}{r.created_at?` · ${new Date(r.created_at).toLocaleDateString()}`:''}</p>{!r.sample_mode&&<p className="visibility-note">{r.is_public?'This report is listed publicly. The submitted idea, queries and evidence can be viewed by anyone.':`Anyone with this unlisted link can view the report; the link is not an access-control boundary. ${r.saved?'Saved reports expire after seven days.':'This unsaved report link expires after one hour.'}`}</p>}</div><button className="quiet-button" onClick={()=>navigator.clipboard?.writeText(location.href)}>Copy report link</button></header>
  <section className="score-panel"><div className="score-block"><span>Search overlap</span><strong>{r.overlap_score}<small>/100</small></strong><div className="meter"><i style={{width:`${r.overlap_score}%`}}/></div><p>{r.interpretation}</p></div><div className="signal-block"><span>Search-based novelty signal</span><strong>{r.novelty_signal}<small>/100</small></strong><p>Calculated as 100 minus overlap. Limited overlap can reflect query or source coverage.</p></div><div className="confidence-block"><span>Evidence confidence</span><strong>{r.confidence_score}<small>/100</small></strong><b>{r.confidence_label} confidence</b><p>Measures result coverage and metadata completeness.</p></div></section>
  <p className="disclaimer">{r.summary.disclaimer}</p>
  <section className="report-section"><div className="section-head"><div><p className="kicker">Claim-by-claim</p><h2>Evidence map</h2></div><p>Select a claim to see the strongest text matches.</p></div>{r.summary.least_covered_claims.length>0&&<div className="least-covered"><strong>Areas needing a deeper search</strong><span>Low coverage points to more review work. It does not prove a gap.</span><ul>{r.summary.least_covered_claims.map(c=><li key={c.id}>{c.text}<small>{c.coverage_label} coverage · {c.coverage_score}%</small></li>)}</ul></div>}{r.claims.length?<div className="claim-list">{r.claims.map(c=><details key={c.id} className="claim-row"><summary><span><b>{c.text}</b><small>{c.matches.length} matching records · {c.matched_terms.join(', ')||'No clear term matches'}</small></span><span className={'coverage '+c.coverage_label.toLowerCase()}>{c.coverage_label}<small>{c.coverage_score}%</small></span></summary><div className="claim-matches">{c.matches.length?c.matches.map(m=><article key={m.evidence_id}><div><strong>{m.title}</strong><span>{m.source_type} · {m.similarity_score}%</span></div><p>{m.excerpt||'No excerpt available.'}</p>{m.url&&<a href={m.url} target="_blank" rel="noreferrer">Open source</a>}</article>):<p className="empty-state">No matching evidence was returned for this claim. That is a prompt for deeper searching, not proof of a research gap.</p>}</div></details>)}</div>:<p className="empty-state">No key claims were supplied.</p>}</section>
  <section className="report-section"><div className="section-head"><div><p className="kicker">Academic literature</p><h2>Related papers <span className="count">{r.papers.length}</span></h2></div></div>{r.papers.length?<div className="evidence-list">{r.papers.map(e=><EvidenceCard key={e.id} item={e}/>)}</div>:<p className="empty-state">No paper records were returned. Check the exact queries below and search academic indexes manually.</p>}</section>
  <section className="report-section"><div className="section-head"><div><p className="kicker">Patent records</p><h2>Related patents <span className="count">{r.patents.length}</span></h2></div></div>{r.patents.length?<div className="evidence-list">{r.patents.map(e=><EvidenceCard key={e.id} item={e}/>)}</div>:<p className="empty-state">No patent records were returned. Patent databases and jurisdictions can have gaps.</p>}</section>
  {r.web_results.length>0&&<section className="report-section"><div className="section-head"><div><p className="kicker">Separate source type</p><h2>Public implementations <span className="count">{r.web_results.length}</span></h2></div><p>Web results are not academic or patent evidence.</p></div><div className="evidence-list">{r.web_results.map(e=><EvidenceCard key={e.id} item={e}/>)}</div></section>}
  <section className="report-section"><div className="section-head"><div><p className="kicker">When related work appeared</p><h2>Prior art timeline</h2></div></div>{r.timeline.length?<div className="timeline">{r.timeline.map((t,i)=><div className="timeline-row" key={`${t.year}-${i}`}><strong>{t.year}</strong><span className={t.source_type}>{t.source_type}</span><span>{t.url?<a href={t.url} target="_blank" rel="noreferrer">{t.title}</a>:t.title}</span></div>)}</div>:<p className="empty-state">No usable publication or priority years were returned.</p>}</section>
  <section className="report-section"><div className="section-head"><div><p className="kicker">People and organizations</p><h2>Who is active in these results?</h2></div><p>Counts describe retrieved records only.</p></div><div className="method-grid"><div><h3>Patent assignees</h3><ul className="people-list">{(r.assignee_summary||[]).map(x=><li key={x.name}>{x.name}<span>{x.count}</span></li>)}</ul>{!(r.assignee_summary||[]).length&&<p className="hint">No assignee names returned.</p>}</div><div><h3>Inventors</h3><ul className="people-list">{(r.inventor_summary||[]).map(x=><li key={x.name}>{x.name}<span>{x.count}</span></li>)}</ul>{!(r.inventor_summary||[]).length&&<p className="hint">No inventor names returned.</p>}</div><div><h3>Paper authors</h3><ul className="people-list">{(r.author_summary||[]).map(x=><li key={x.name}>{x.name}<span>{x.count}</span></li>)}</ul>{!(r.author_summary||[]).length&&<p className="hint">No author names returned.</p>}</div></div></section>
  {r.ai_analysis.claim_explanations?.length||r.ai_analysis.areas_needing_deeper_search?.length||r.ai_analysis.executive_summary?<section className="report-section"><div className="section-head"><div><p className="kicker">Optional AI notes</p><h2>Evidence explanation</h2></div><p>AI text explains saved evidence; it does not assign scores.</p></div><p className="ai-note">{r.ai_analysis.executive_summary}</p>{r.ai_analysis.claim_explanations?.map((x,i)=><article className="ai-explanation" key={`${x.claim_id}-${i}`}><strong>{r.claims.find(c=>c.id===x.claim_id)?.text||'Research claim'} · {x.assessment}</strong><p>{x.explanation}</p>{x.limitations.length>0&&<small>Limits: {x.limitations.join(' · ')}</small>}</article>)}{r.ai_analysis.areas_needing_deeper_search?.map((x,i)=><article className="ai-explanation" key={`deeper-${i}`}><strong>Search further: {r.claims.find(c=>c.id===x.claim_id)?.text||'Research claim'}</strong><p>{x.reason}</p>{x.suggested_queries.map((q,j)=><code className="suggested-query" key={j}>{q}</code>)}</article>)}</section>:null}
  <NoveltyWorkspace report={r} id={id} reportBase={reportBase}/>
  <ResearchWorkspaceSync key={id} report={r} id={id}/>
  <ResearchToolkit key={id+recordRevision} report={r} id={id}/>
  <Suspense fallback={<section className="report-section" role="status">Loading research tools…</section>}><ResearchDefenseLab key={id+recordRevision} report={r} id={id}/></Suspense>
  <Suspense fallback={<section className="report-section" role="status">Loading integrity tools…</section>}><ResearchIntegrityLab key={id+recordRevision} report={r} id={id}/></Suspense>
  <section className="report-section"><div className="section-head"><div><p className="kicker">Reproducibility</p><h2>Searches and scoring</h2></div></div><details open><summary>Exact searches used</summary><ul className="query-list">{r.queries.map((q,i)=><li key={i}><span>{q.engine}</span><code>{q.query}</code></li>)}</ul></details><div className="method-grid"><div><h3>Overlap formula</h3><code>0.50 × top match + 0.30 × mean top five + 0.20 × high-match breadth</code></div><div><h3>Per-record similarity</h3><code>0.60 × TF-IDF + 0.25 × claim coverage + 0.15 × phrase coverage</code></div><div><h3>Limits</h3><p>Search results are incomplete, text similarity is not a legal or scientific judgment, and weak results may reflect query coverage or inaccessible sources.</p></div></div>{r.warnings.map((w,i)=><p key={i} className="warning-line">{w}</p>)}{r.ai_analysis.warnings.map((w,i)=><p key={`ai-${i}`} className="warning-line">{w}</p>)}</section>
  <div className="report-end"><span>Methodology {r.methodology_version} · {r.credential_mode} mode</span><Link to={homePath}>Search another idea</Link></div>
 </div>
}
