import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {noveltyApi} from '../api/novelty';

const sampleClaims=[{claim:'Detect crop disease on a low-power phone.',source:'Compact leaf-image models for mobile devices',shared:'Mobile inference and crop disease detection',unanswered:'Does it run under the proposed memory and energy limits?'},{claim:'Improve the model without uploading farm images.',source:'Federated learning across agricultural image collections',shared:'Federated updates and local image storage',unanswered:'Does the proposed combination add a measured privacy benefit?'},{claim:'Refer uncertain predictions for expert review.',source:'Confidence thresholds in plant disease classification',shared:'Prediction confidence and uncertainty thresholds',unanswered:'Does referral improve the outcome for farmers?'}];
export function ResearchLandingPage(){const [selected,setSelected]=useState(0);const status=useQuery({queryKey:['demo-status'],queryFn:noveltyApi.status,staleTime:30000});const live=status.data?.hosted_mode==='available';const claim=sampleClaims[selected];return <div className="wrap research-landing">
  <section className="landing-hero"><div><p className="kicker">ResearchScope · Evidence before commitment</p><h1>Find the work closest to your idea.</h1><p className="lede">Compare research claims with papers, patents, and public implementations. Keep the evidence, open questions, and next experiments together.</p><div className="landing-actions"><Link className="primary-button inline-button" to={live?'/research-scope':'/research-scope/reports/sample'}>{live?'Start a research check':'View sample report'}</Link><Link className="quiet-button" to={live?'/research-scope/reports/sample':'/research-scope'}>{live?'View sample report':'Draft your idea'}</Link></div><p className="hint" role="status">{live?'Live research search is available. Review provider consent before submitting.':status.isPending?'Checking live search availability. The sample needs no search credentials.':'Live search is currently unavailable. You can explore the sample or prepare a draft.'}</p></div><aside className="landing-preview"><p className="preview-label">Fictional example · not research evidence</p><h2>One claim. A closer question.</h2><p>“Improve the model without uploading farm images.”</p><div className="preview-comparison"><span>Already seen in the example</span><p>Federated updates and local image storage</p><span>Still needs verification</span><p>What benefit does this combination deliver under your conditions?</p></div><Link to="/research-scope/reports/sample?view=claims">Explore the claim evidence map →</Link></aside></section>
  <section className="landing-demo"><div><h2>Follow a claim back to its evidence.</h2><p>A similar title is a starting point. Inspect the excerpt, read the original work, and decide which part of your contribution remains defensible.</p><p className="hint">The examples here are fictional. ResearchScope does not certify novelty or determine patentability.</p></div><div className="claim-demo"><fieldset><legend>Choose an example claim</legend>{sampleClaims.map((item,index)=><label key={item.claim} className={selected===index?'chosen':''}><input type="radio" name="example-claim" checked={selected===index} onChange={()=>setSelected(index)}/>{item.claim}</label>)}</fieldset><article aria-live="polite"><h3>{claim.source}</h3><dl><div><dt>Shared concepts</dt><dd>{claim.shared}</dd></div><div><dt>Question to investigate</dt><dd>{claim.unanswered}</dd></div></dl></article></div></section>
  <section className="landing-editorial"><h2>Finding a match is the beginning.</h2><div><article><h3>Read with a purpose</h3><p>Collect the closest sources, distinguish publication versions, and record why a study belongs in your review.</p><Link to="/research-scope/reports/sample?view=evidence">Explore evidence →</Link></article><article><h3>Make the difference testable</h3><p>Narrow the claim, check baseline fairness, and connect the contribution to an experiment and acceptance criterion.</p><Link to="/research-scope/reports/sample?view=study">Explore study planning →</Link></article><article><h3>Keep the decision traceable</h3><p>Document open questions, assign checks, and export the evidence behind a proceed, revise, or pause decision.</p><Link to="/research-scope/reports/sample?view=review">Explore research review →</Link></article></div></section>
  <section className="landing-limits"><h2>Know what a search can tell you.</h2><p>Scores describe overlap in retrieved text. Low overlap can mean a limited query, inaccessible full text, or missing coverage. It is not proof that an idea is new.</p><p>Added sources and researcher judgments remain separate from the original search scores. The report keeps the exact queries and source warnings available in Record.</p></section>
  <section className="landing-faq"><h2>Before you start</h2><details><summary>Can I try it without a live search?</summary><p>Yes. The prepared sample demonstrates the report and planning tools with fictional evidence and no provider search calls.</p></details><details><summary>Where does my idea go?</summary><p>A live search sends the submitted idea to the configured search provider. Optional Groq processing is explained in the consent form. Avoid submitting unpublished confidential work that should not leave your device. The separate private local workspace compares notes on this device without searching the web.</p><Link to="/research-scope/private">Open private local workspace</Link></details><details><summary>How long is a report kept?</summary><p>Saved reports expire after 12 days. Unsaved links expire after one hour. Local tool records remain in this browser until removed; export them for a durable copy.</p></details><details><summary>Can someone else read my report?</summary><p>Unlisted links can be read by anyone who has the link. Public reports are listed publicly. Shared planning records require an explicit publishing action; owner and reviewer links grant additional capabilities.</p></details></section>
  <section className="landing-close"><h2>Start with the closest work.</h2><Link className="primary-button inline-button" to={live?'/research-scope':'/research-scope/reports/sample'}>{live?'Start a research check':'View sample report'}</Link></section><footer className="research-footer"><span>ResearchScope · Trace your research decisions</span><Link to="/research-scope">Draft an idea</Link></footer>
 </div>;}
