import {useQuery} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api/client';
import {AnalysisForm} from '../components/AnalysisForm';
import {lazy} from 'react';
const ReportView=lazy(()=>import('../components/ReportView').then(m=>({default:m.ReportView})));
export function VentureHome(){return <><div className="home-heading"><h1>Find your next business opportunity.</h1><p>VentureAtlas connects market evidence with the assumptions, experiments and decisions behind your launch.</p></div><div className="home-grid"><AnalysisForm/><aside className="research-note"><h2>Evidence before commitment</h2><p>Explore competitors and customer needs. Compare research sources. Build a decision trail your team can inspect.</p><p>Start with the Pune coworking sample. Synthetic examples are labeled throughout.</p><Link className="secondary" to="/reports">Open saved reports</Link></aside></div></>}
export function VentureReport(){const {id=''}=useParams();const q=useQuery({queryKey:['report',id],queryFn:()=>api.get(id),refetchInterval:q=>q.state.data&&['queued','running'].includes(q.state.data.status)?1800:false});if(q.isPending)return <p role="status">Loading market report…</p>;if(q.isError)return <p role="alert">{q.error.message}</p>;const r=q.data;if(r.status!=='complete')return <section className="report-section"><h1>{r.status==='failed'?'Analysis stopped':'Building your market report'}</h1><p role="status">{r.status==='failed'?r.error_message:r.stage}</p><progress max={100} value={r.progress}/><Link to="/">Start an analysis</Link></section>;return <ReportView report={r}/>}
export function VentureReports(){const q=useQuery({queryKey:['recent-reports'],queryFn:api.recent});return <><h1>Saved market reports</h1>{q.isPending?<p>Loading…</p>:q.isError?<p role="alert">{q.error.message}</p>:<div className="research-evidence-list">{q.data.map(r=><article key={r.id}><h2><Link to={`/reports/${r.id}`}>{r.business_category} in {r.city}</Link></h2><p>{r.country} · {r.data_mode} · {r.overall_score}/100 · {new Date(r.created_at).toLocaleString()}</p></article>)}{!q.data.length&&<p>No saved reports. <Link to="/">Create the sample analysis.</Link></p>}</div>}</>}
