import {z} from 'zod';
import type {Report} from '../types/analysis';
import type {ResearchRun,ResearchTool} from '../types/research';
export const noteSchema=z.object({id:z.string(),kind:z.enum(['Finding','Assumption','Decision']),text:z.string().min(3).max(600),sources:z.array(z.string()).max(20)});
export type StrategyNote=z.infer<typeof noteSchema>;
export const experimentSchema=z.object({id:z.string(),name:z.string().min(3).max(100),assumption:z.string().min(3).max(600),impact:z.number().int().min(1).max(5),uncertainty:z.number().int().min(1).max(5),cost:z.number().finite().nonnegative(),hours:z.number().finite().nonnegative(),currency:z.enum(['INR','USD','EUR','GBP']),measure:z.string().min(3).max(600),result:z.string().max(1000)});
export type RankedExperiment=z.infer<typeof experimentSchema>;
export function prioritizeExperiments(items:RankedExperiment[],budget:number,hours:number,currency:string){const ranked=items.filter(v=>v.currency===currency).map(v=>({...v,score:v.impact*v.uncertainty/(1+v.hours/Math.max(hours,1)+(budget>0?v.cost/budget:v.cost===0?0:Infinity))})).sort((a,b)=>b.score-a.score||a.cost-b.cost);let money=Math.max(0,budget),time=Math.max(0,hours);return ranked.map(v=>{const included=v.cost<=money&&v.hours<=time;if(included){money-=v.cost;time-=v.hours}return {...v,included}})}
export function evidenceNodes(r:Report){return r.evidence.map(e=>({id:e.id,title:e.title,detail:e.snippet||'',url:e.source_url,engine:e.engine}));}
export const strategySections=[['graph','Evidence connections'],['conflicts','Contradictory evidence'],['gaps','Research gaps'],['personas','Customer personas'],['team','Team workspace'],['changes','Market changes'],['offers','Competitor offers'],['regulations','Regulatory readiness'],['experiments','Experiment priorities'],['pitch','Venture pitch']] as const;
export function conflicts(r:Report){const out:{id:string;title:string;basis:string;check:string;links:{title:string;url:string}[]}[]=[];
 const negative=r.review_topics.flatMap(t=>t.excerpts.filter(e=>e.rating<=3).map(e=>({topic:t.topic,review:e})));
 if(r.sections.trends?.status==='complete'&&r.sections.reviews?.status==='complete'&&r.component_scores.demand>=60&&negative.length>=2)out.push({id:'demand-friction',title:'Search interest and customer friction coexist',basis:`Demand score ${r.component_scores.demand}/100; at least two sampled negative review excerpts. These measure different things.`,check:'Interview customers about unmet needs, rather than assuming rising interest means satisfaction.',links:negative.slice(0,5).map(e=>({title:e.topic+': '+e.review.competitor,url:e.review.source_url||'#'}))});
 if(r.sections.news?.status==='complete'){const positive=r.news.filter(n=>n.sentiment==='positive'),negativeNews=r.news.filter(n=>n.sentiment==='negative');if(positive.length&&negativeNews.length)out.push({id:'news-mixed',title:'News snippets contain opposing signals',basis:`${positive.length} positively labeled and ${negativeNews.length} negatively labeled snippets. Labels are keyword matches.`,check:'Read the articles and compare dates, scope and subjects before interpreting the disagreement.',links:[positive[0],negativeNews[0]].map(n=>({title:n.title,url:n.source_url||'#'}))})}
 for(const topic of r.review_topics){const good=topic.excerpts.find(e=>e.rating>=4),bad=topic.excerpts.find(e=>e.rating<=3);if(good&&bad)out.push({id:'topic-'+topic.topic,title:`Different experiences of ${topic.topic}`,basis:'Saved excerpts for this topic include both a high-rated and a low-rated review. Whole-review ratings may cover several topics.',check:'Check venue, review date and customer context; record whether the accounts can coexist.',links:[good,bad].map(e=>({title:e.competitor+' · '+e.rating+' stars',url:e.source_url||'#'}))})}return out;
}
export const conflictSchema=z.object({id:z.string(),finding:z.string(),resolution:z.enum(['Unreviewed','Needs investigation','Context explains difference','Evidence insufficient']),notes:z.string().max(1200)});
export function researchGaps(r:Report,runs:ResearchRun[],budget:number){const needs:[ResearchTool,string,string,number][]=[['forums','Customer concerns','Read discussion context beyond reviews.',1],['autocomplete','Customer search language','Inspect suggestions without assuming search volume.',3],['events','Temporary local activity','Check event dates and venues.',1],['jobs','Operational skills','Inspect role requirements and missing salary fields.',1],['shopping','Equipment price assumptions','Select comparable products and verify conditions.',1],['directions','Accessibility assumptions','Compare selected destinations from a public landmark.',3],['hotels','Hospitality price context','Compare equivalent stays over three dates.',3],['flights','Visitor connectivity','Inspect a relevant airport pair.',1],['images','Visual positioning','Manually review relevant competitor imagery.',1],['scholar','Research applicability','Read full papers before using findings.',1]];
 return needs.map(([tool,title,why,cost],i)=>{const useful=runs.filter(j=>j.tool===tool&&(j.status==='complete'||j.status==='partial')&&j.batches.some(b=>b.rows.length));const latest=useful.sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at))[0];return {tool,title,why,cost,priority:latest?0:needs.length-i,status:latest?'Collected; inspect relevance':'Unanswered',fits:cost<=budget}}).sort((a,b)=>b.priority-a.priority);
}
export function reportDigest(a:Report,b:Report){if(a.input.business_category.toLowerCase()!==b.input.business_category.toLowerCase()||a.input.city.toLowerCase()!==b.input.city.toLowerCase()||a.input.country!==b.input.country||a.data_mode!==b.data_mode)return {compatible:false,lines:['Choose reports for the same category, city, country and data mode.']};if(Date.parse(a.created_at)>Date.parse(b.created_at))return {compatible:false,lines:['Choose a baseline saved before the current report.']};const old=new Map(a.competitors.map(c=>[c.data_id||c.name,c])),current=new Map(b.competitors.map(c=>[c.data_id||c.name,c]));const lines:string[]=[];for(const [id,c] of current){const previous=old.get(id);if(!previous)lines.push(`Newly returned competitor: ${c.name}`);else{if(previous.rating!==c.rating)lines.push(`${c.name}: rating ${previous.rating??'unknown'} → ${c.rating??'unknown'}`);if(previous.review_count!==c.review_count)lines.push(`${c.name}: review count ${previous.review_count} → ${c.review_count}`);if(previous.price!==c.price)lines.push(`${c.name}: price label ${previous.price||'unknown'} → ${c.price||'unknown'}`)}}for(const [id,c] of old)if(!current.has(id))lines.push(`Not returned in later sample: ${c.name}`);for(const key of Object.keys(a.component_scores) as (keyof Report['component_scores'])[])if(a.component_scores[key]!==b.component_scores[key])lines.push(`${key.replaceAll('_',' ')} score: ${a.component_scores[key]} → ${b.component_scores[key]}`);return {compatible:true,lines:lines.length?lines:['No tracked differences in the saved samples.']}}
function stableInput(input:ResearchRun['input']){return JSON.stringify(Object.entries(input).filter(([key])=>key!=='refresh').sort(([a],[b])=>a.localeCompare(b)))}
export function researchDigest(a:ResearchRun,b:ResearchRun){if(a.tool!==b.tool||a.data_mode!==b.data_mode||stableInput(a.input)!==stableInput(b.input))return {compatible:false,lines:['Inputs or data mode differ. Repeat the same query and conditions before comparing returned observations.']};if(Date.parse(a.created_at)>Date.parse(b.created_at))return {compatible:false,lines:['Choose a baseline saved before the later run.']};const rows=(run:ResearchRun)=>new Map(run.batches.flatMap(batch=>batch.rows.map(row=>[JSON.stringify([batch.label,row.title,row.url]),row] as const)));const old=rows(a),current=rows(b);const lines:string[]=[];for(const [id,r] of current){const before=old.get(id);if(!before)lines.push(`Newly returned: ${r.title}`);else if(JSON.stringify(before.meta)!==JSON.stringify(r.meta)||before.detail!==r.detail)lines.push(`Changed returned details: ${r.title}`)}for(const [id,r] of old)if(!current.has(id))lines.push(`Not returned in later sample: ${r.title}`);return {compatible:true,lines:lines.length?lines:['No tracked differences in the saved samples.']}}
